-- CONTEXT:
-- Adds the first internal DCX tracker model for strategy, operations, battles, tasks,
-- and the activity updates attached to them. This is intentionally small: one nested
-- work-item table and one update stream table.

BEGIN;

CREATE TABLE IF NOT EXISTS public.stephen_dcx_admin_tracker_work_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text NOT NULL DEFAULT '',
    current_state text NOT NULL DEFAULT '',
    work_item_level text NOT NULL,
    pillar text NOT NULL,
    pillars text[] NOT NULL DEFAULT ARRAY['building']::text[],
    item_status text NOT NULL DEFAULT 'not_started',
    parent_work_item_id bigint REFERENCES public.stephen_dcx_admin_tracker_work_items(id) ON DELETE SET NULL,
    created_by_user_id bigint REFERENCES public.stephen_dcx_users(id) ON DELETE SET NULL,
    updated_by_user_id bigint REFERENCES public.stephen_dcx_users(id) ON DELETE SET NULL,
    created_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    updated_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    CONSTRAINT stephen_dcx_admin_tracker_work_items_level_check
        CHECK (work_item_level IN ('long_term', 'strategy', 'operation', 'battle', 'task')),
    CONSTRAINT stephen_dcx_admin_tracker_work_items_pillar_check
        CHECK (pillar IN ('legibility', 'investors', 'building', 'customers', 'other')),
    CONSTRAINT stephen_dcx_admin_tracker_work_items_pillars_check
        CHECK (
            cardinality(pillars) > 0
            AND pillars <@ ARRAY['legibility', 'investors', 'building', 'customers', 'other']::text[]
        ),
    CONSTRAINT stephen_dcx_admin_tracker_work_items_status_check
        CHECK (item_status IN ('not_started', 'active', 'waiting', 'done'))
);

CREATE INDEX IF NOT EXISTS stephen_dcx_admin_tracker_work_items_parent_idx
ON public.stephen_dcx_admin_tracker_work_items(parent_work_item_id, id);

CREATE INDEX IF NOT EXISTS stephen_dcx_admin_tracker_work_items_status_idx
ON public.stephen_dcx_admin_tracker_work_items(item_status, updated_at_ts_ms DESC, id DESC);

CREATE INDEX IF NOT EXISTS stephen_dcx_admin_tracker_work_items_pillar_idx
ON public.stephen_dcx_admin_tracker_work_items(pillar, item_status, updated_at_ts_ms DESC, id DESC);

CREATE INDEX IF NOT EXISTS stephen_dcx_admin_tracker_work_items_pillars_gin_idx
ON public.stephen_dcx_admin_tracker_work_items
USING GIN (pillars);

CREATE INDEX IF NOT EXISTS stephen_dcx_admin_tracker_work_items_level_idx
ON public.stephen_dcx_admin_tracker_work_items(work_item_level, updated_at_ts_ms DESC, id DESC);

CREATE TABLE IF NOT EXISTS public.stephen_dcx_admin_tracker_updates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_item_id bigint NOT NULL REFERENCES public.stephen_dcx_admin_tracker_work_items(id) ON DELETE CASCADE,
    author_user_id bigint REFERENCES public.stephen_dcx_users(id) ON DELETE SET NULL,
    update_kind text NOT NULL DEFAULT 'note',
    update_body text NOT NULL,
    created_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    updated_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    CONSTRAINT stephen_dcx_admin_tracker_updates_kind_check
        CHECK (update_kind IN ('note', 'progress', 'blocker', 'decision', 'question', 'action'))
);

CREATE INDEX IF NOT EXISTS stephen_dcx_admin_tracker_updates_work_item_created_idx
ON public.stephen_dcx_admin_tracker_updates(work_item_id, created_at_ts_ms DESC, id DESC);

CREATE INDEX IF NOT EXISTS stephen_dcx_admin_tracker_updates_author_created_idx
ON public.stephen_dcx_admin_tracker_updates(author_user_id, created_at_ts_ms DESC, id DESC);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'stephen_dcx_admin_tracker_work_items_set_updated_at_ts_ms'
    ) THEN
        CREATE TRIGGER stephen_dcx_admin_tracker_work_items_set_updated_at_ts_ms
        BEFORE UPDATE ON public.stephen_dcx_admin_tracker_work_items
        FOR EACH ROW
        EXECUTE FUNCTION public.stephen_dcx_set_updated_at_ts_ms();
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'stephen_dcx_admin_tracker_updates_set_updated_at_ts_ms'
    ) THEN
        CREATE TRIGGER stephen_dcx_admin_tracker_updates_set_updated_at_ts_ms
        BEFORE UPDATE ON public.stephen_dcx_admin_tracker_updates
        FOR EACH ROW
        EXECUTE FUNCTION public.stephen_dcx_set_updated_at_ts_ms();
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_roles
        WHERE rolname = 'dcxagent_user'
    ) THEN
        GRANT SELECT, INSERT, UPDATE, DELETE
        ON TABLE
            public.stephen_dcx_admin_tracker_work_items,
            public.stephen_dcx_admin_tracker_updates
        TO dcxagent_user;

        GRANT USAGE, SELECT
        ON SEQUENCE
            public.stephen_dcx_admin_tracker_work_items_id_seq,
            public.stephen_dcx_admin_tracker_updates_id_seq
        TO dcxagent_user;
    END IF;
END $$;

COMMIT;
