-- CONTEXT:
-- Adds the first clean DCX network slice: profile-facing settings, follows,
-- app-private feed posts/replies, and direct-message threads/messages.
-- Tables use the standard DCX bigint identity primary key plus millisecond
-- Unix created/updated timestamps.

BEGIN;

ALTER TABLE public.stephen_dcx_users
ADD COLUMN IF NOT EXISTS network_dm_acceptance_mode text NOT NULL DEFAULT 'everyone',
ADD COLUMN IF NOT EXISTS network_profile_image_url text NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS network_profile_image_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'stephen_dcx_users_network_dm_acceptance_mode_check'
    ) THEN
        ALTER TABLE public.stephen_dcx_users
        ADD CONSTRAINT stephen_dcx_users_network_dm_acceptance_mode_check
        CHECK (network_dm_acceptance_mode IN ('everyone', 'following', 'none'));
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'stephen_dcx_users_network_profile_image_url_length_check'
    ) THEN
        ALTER TABLE public.stephen_dcx_users
        ADD CONSTRAINT stephen_dcx_users_network_profile_image_url_length_check
        CHECK (length(network_profile_image_url) <= 2048);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.stephen_dcx_network_follows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_user_id bigint NOT NULL REFERENCES public.stephen_dcx_users(id) ON DELETE CASCADE,
    followed_user_id bigint NOT NULL REFERENCES public.stephen_dcx_users(id) ON DELETE CASCADE,
    follow_status text NOT NULL DEFAULT 'active',
    follow_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    updated_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    CONSTRAINT stephen_dcx_network_follows_distinct_users_check CHECK (follower_user_id <> followed_user_id),
    CONSTRAINT stephen_dcx_network_follows_status_check CHECK (follow_status IN ('active', 'inactive')),
    CONSTRAINT stephen_dcx_network_follows_user_pair_key UNIQUE (follower_user_id, followed_user_id)
);

CREATE INDEX IF NOT EXISTS stephen_dcx_network_follows_follower_active_idx
ON public.stephen_dcx_network_follows(follower_user_id, follow_status, updated_at_ts_ms DESC, id DESC);

CREATE INDEX IF NOT EXISTS stephen_dcx_network_follows_followed_active_idx
ON public.stephen_dcx_network_follows(followed_user_id, follow_status, updated_at_ts_ms DESC, id DESC);

CREATE TABLE IF NOT EXISTS public.stephen_dcx_network_feed_posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_user_id bigint NOT NULL REFERENCES public.stephen_dcx_users(id) ON DELETE CASCADE,
    post_status text NOT NULL DEFAULT 'active',
    visibility_status text NOT NULL DEFAULT 'app_public',
    source_kind text NOT NULL DEFAULT 'manual',
    source_id bigint,
    post_text text NOT NULL DEFAULT '',
    language_code text NOT NULL DEFAULT 'en',
    translations_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    moderation_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    post_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    updated_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    CONSTRAINT stephen_dcx_network_feed_posts_status_check CHECK (post_status IN ('active', 'withdrawn', 'hidden')),
    CONSTRAINT stephen_dcx_network_feed_posts_visibility_check CHECK (visibility_status IN ('app_public')),
    CONSTRAINT stephen_dcx_network_feed_posts_source_kind_check CHECK (source_kind IN ('manual', 'ai_chat', 'trade', 'system')),
    CONSTRAINT stephen_dcx_network_feed_posts_text_length_check CHECK (length(btrim(post_text)) BETWEEN 1 AND 500),
    CONSTRAINT stephen_dcx_network_feed_posts_language_code_check CHECK (language_code ~ '^[a-z]{2,3}(-[a-z0-9]{2,8})?$')
);

CREATE INDEX IF NOT EXISTS stephen_dcx_network_feed_posts_catalog_idx
ON public.stephen_dcx_network_feed_posts(post_status, visibility_status, created_at_ts_ms DESC, id DESC);

CREATE INDEX IF NOT EXISTS stephen_dcx_network_feed_posts_author_idx
ON public.stephen_dcx_network_feed_posts(author_user_id, created_at_ts_ms DESC, id DESC);

CREATE TABLE IF NOT EXISTS public.stephen_dcx_network_feed_replies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_post_id bigint NOT NULL REFERENCES public.stephen_dcx_network_feed_posts(id) ON DELETE CASCADE,
    author_user_id bigint NOT NULL REFERENCES public.stephen_dcx_users(id) ON DELETE CASCADE,
    reply_status text NOT NULL DEFAULT 'active',
    reply_text text NOT NULL DEFAULT '',
    language_code text NOT NULL DEFAULT 'en',
    translations_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    moderation_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    reply_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    updated_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    CONSTRAINT stephen_dcx_network_feed_replies_status_check CHECK (reply_status IN ('active', 'withdrawn', 'hidden')),
    CONSTRAINT stephen_dcx_network_feed_replies_text_length_check CHECK (length(btrim(reply_text)) BETWEEN 1 AND 500),
    CONSTRAINT stephen_dcx_network_feed_replies_language_code_check CHECK (language_code ~ '^[a-z]{2,3}(-[a-z0-9]{2,8})?$')
);

CREATE INDEX IF NOT EXISTS stephen_dcx_network_feed_replies_post_idx
ON public.stephen_dcx_network_feed_replies(feed_post_id, created_at_ts_ms ASC, id ASC);

CREATE INDEX IF NOT EXISTS stephen_dcx_network_feed_replies_author_idx
ON public.stephen_dcx_network_feed_replies(author_user_id, created_at_ts_ms DESC, id DESC);

CREATE TABLE IF NOT EXISTS public.stephen_dcx_network_dm_threads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_user_id_1 bigint NOT NULL REFERENCES public.stephen_dcx_users(id) ON DELETE CASCADE,
    participant_user_id_2 bigint NOT NULL REFERENCES public.stephen_dcx_users(id) ON DELETE CASCADE,
    thread_status text NOT NULL DEFAULT 'open',
    thread_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    updated_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    CONSTRAINT stephen_dcx_network_dm_threads_participant_order_check CHECK (participant_user_id_1 < participant_user_id_2),
    CONSTRAINT stephen_dcx_network_dm_threads_status_check CHECK (thread_status IN ('open', 'archived', 'blocked')),
    CONSTRAINT stephen_dcx_network_dm_threads_participants_key UNIQUE (participant_user_id_1, participant_user_id_2)
);

CREATE INDEX IF NOT EXISTS stephen_dcx_network_dm_threads_participant_1_idx
ON public.stephen_dcx_network_dm_threads(participant_user_id_1, thread_status, updated_at_ts_ms DESC, id DESC);

CREATE INDEX IF NOT EXISTS stephen_dcx_network_dm_threads_participant_2_idx
ON public.stephen_dcx_network_dm_threads(participant_user_id_2, thread_status, updated_at_ts_ms DESC, id DESC);

CREATE TABLE IF NOT EXISTS public.stephen_dcx_network_dm_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dm_thread_id bigint NOT NULL REFERENCES public.stephen_dcx_network_dm_threads(id) ON DELETE CASCADE,
    sender_user_id bigint NOT NULL REFERENCES public.stephen_dcx_users(id) ON DELETE CASCADE,
    message_status text NOT NULL DEFAULT 'active',
    raw_message_text text NOT NULL DEFAULT '',
    canonical_message_text text NOT NULL DEFAULT '',
    language_code text NOT NULL DEFAULT 'en',
    translations_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    moderation_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    message_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    updated_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    CONSTRAINT stephen_dcx_network_dm_messages_status_check CHECK (message_status IN ('active', 'blocked', 'hidden')),
    CONSTRAINT stephen_dcx_network_dm_messages_text_length_check CHECK (length(btrim(raw_message_text)) BETWEEN 1 AND 2000),
    CONSTRAINT stephen_dcx_network_dm_messages_language_code_check CHECK (language_code ~ '^[a-z]{2,3}(-[a-z0-9]{2,8})?$')
);

CREATE INDEX IF NOT EXISTS stephen_dcx_network_dm_messages_thread_idx
ON public.stephen_dcx_network_dm_messages(dm_thread_id, created_at_ts_ms ASC, id ASC);

CREATE INDEX IF NOT EXISTS stephen_dcx_network_dm_messages_sender_idx
ON public.stephen_dcx_network_dm_messages(sender_user_id, created_at_ts_ms DESC, id DESC);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'stephen_dcx_network_follows_set_updated_at_ts_ms'
    ) THEN
        CREATE TRIGGER stephen_dcx_network_follows_set_updated_at_ts_ms
        BEFORE UPDATE ON public.stephen_dcx_network_follows
        FOR EACH ROW
        EXECUTE FUNCTION public.stephen_dcx_set_updated_at_ts_ms();
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'stephen_dcx_network_feed_posts_set_updated_at_ts_ms'
    ) THEN
        CREATE TRIGGER stephen_dcx_network_feed_posts_set_updated_at_ts_ms
        BEFORE UPDATE ON public.stephen_dcx_network_feed_posts
        FOR EACH ROW
        EXECUTE FUNCTION public.stephen_dcx_set_updated_at_ts_ms();
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'stephen_dcx_network_feed_replies_set_updated_at_ts_ms'
    ) THEN
        CREATE TRIGGER stephen_dcx_network_feed_replies_set_updated_at_ts_ms
        BEFORE UPDATE ON public.stephen_dcx_network_feed_replies
        FOR EACH ROW
        EXECUTE FUNCTION public.stephen_dcx_set_updated_at_ts_ms();
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'stephen_dcx_network_dm_threads_set_updated_at_ts_ms'
    ) THEN
        CREATE TRIGGER stephen_dcx_network_dm_threads_set_updated_at_ts_ms
        BEFORE UPDATE ON public.stephen_dcx_network_dm_threads
        FOR EACH ROW
        EXECUTE FUNCTION public.stephen_dcx_set_updated_at_ts_ms();
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'stephen_dcx_network_dm_messages_set_updated_at_ts_ms'
    ) THEN
        CREATE TRIGGER stephen_dcx_network_dm_messages_set_updated_at_ts_ms
        BEFORE UPDATE ON public.stephen_dcx_network_dm_messages
        FOR EACH ROW
        EXECUTE FUNCTION public.stephen_dcx_set_updated_at_ts_ms();
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_roles
        WHERE rolname = 'dcxagent_user'
    ) THEN
        GRANT SELECT, INSERT, UPDATE, DELETE
        ON TABLE
            public.stephen_dcx_network_follows,
            public.stephen_dcx_network_feed_posts,
            public.stephen_dcx_network_feed_replies,
            public.stephen_dcx_network_dm_threads,
            public.stephen_dcx_network_dm_messages
        TO dcxagent_user;

        GRANT USAGE, SELECT
        ON SEQUENCE
            public.stephen_dcx_network_follows_id_seq,
            public.stephen_dcx_network_feed_posts_id_seq,
            public.stephen_dcx_network_feed_replies_id_seq,
            public.stephen_dcx_network_dm_threads_id_seq,
            public.stephen_dcx_network_dm_messages_id_seq
        TO dcxagent_user;
    END IF;
END $$;

COMMIT;
