-- DCX MVP cross-surface trade chat routing.
-- Run after the market/forum/thread spine migration.
--
-- This patch lets traders choose a default notification channel and lets
-- inbound email/WhatsApp replies route back into private trade conversations
-- by explicit #C thread references.

ALTER TABLE public.stephen_dcx_users
ADD COLUMN IF NOT EXISTS default_interaction_channel text NOT NULL DEFAULT 'app_only';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'stephen_dcx_users_default_interaction_channel_check'
    ) THEN
        ALTER TABLE public.stephen_dcx_users
        ADD CONSTRAINT stephen_dcx_users_default_interaction_channel_check
        CHECK (default_interaction_channel IN ('app_only', 'email', 'whatsapp'));
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.stephen_dcx_trade_thread_participant_routes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_thread_id bigint NOT NULL REFERENCES public.stephen_dcx_trade_threads(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES public.stephen_dcx_users(id) ON DELETE CASCADE,
    current_route_channel text NOT NULL DEFAULT 'app_only',
    current_route_contact_method_id bigint NULL REFERENCES public.stephen_dcx_users_contact_methods(id) ON DELETE SET NULL,
    route_source text NOT NULL DEFAULT 'account_default',
    route_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL,
    updated_at_ts_ms bigint NOT NULL,
    CONSTRAINT stephen_dcx_trade_thread_participant_routes_unique_user_thread
        UNIQUE (trade_thread_id, user_id),
    CONSTRAINT stephen_dcx_trade_thread_participant_routes_channel_check
        CHECK (current_route_channel IN ('app_only', 'email', 'whatsapp')),
    CONSTRAINT stephen_dcx_trade_thread_participant_routes_source_check
        CHECK (route_source IN ('account_default', 'origin_channel', 'latest_reply', 'manual'))
);

CREATE INDEX IF NOT EXISTS stephen_dcx_trade_thread_participant_routes_user_idx
ON public.stephen_dcx_trade_thread_participant_routes(user_id);

CREATE INDEX IF NOT EXISTS stephen_dcx_trade_thread_participant_routes_thread_idx
ON public.stephen_dcx_trade_thread_participant_routes(trade_thread_id);

ALTER TABLE public.stephen_dcx_outbound_interaction_routes
ADD COLUMN IF NOT EXISTS trade_thread_id bigint NULL REFERENCES public.stephen_dcx_trade_threads(id) ON DELETE CASCADE,
ADD COLUMN IF NOT EXISTS recipient_user_id bigint NULL REFERENCES public.stephen_dcx_users(id) ON DELETE CASCADE,
ADD COLUMN IF NOT EXISTS route_channel text NULL,
ADD COLUMN IF NOT EXISTS provider_message_id text NULL,
ADD COLUMN IF NOT EXISTS provider_thread_id text NULL,
ADD COLUMN IF NOT EXISTS route_reference_code text NULL;

CREATE INDEX IF NOT EXISTS stephen_dcx_outbound_interaction_routes_trade_thread_idx
ON public.stephen_dcx_outbound_interaction_routes(trade_thread_id);

CREATE INDEX IF NOT EXISTS stephen_dcx_outbound_interaction_routes_provider_message_idx
ON public.stephen_dcx_outbound_interaction_routes(provider_message_id)
WHERE provider_message_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS stephen_dcx_outbound_interaction_routes_provider_thread_idx
ON public.stephen_dcx_outbound_interaction_routes(provider_thread_id)
WHERE provider_thread_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS stephen_dcx_outbound_interaction_routes_reference_idx
ON public.stephen_dcx_outbound_interaction_routes(route_reference_code)
WHERE route_reference_code IS NOT NULL;
