CREATE TABLE IF NOT EXISTS public.stephen_dcx_channel_origins (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_type text NOT NULL,
    provider_type text NOT NULL,
    provider_account_id text NOT NULL DEFAULT '',
    provider_sender_id text NOT NULL,
    sender_display_handle text NOT NULL DEFAULT '',
    sender_display_name text NOT NULL DEFAULT '',
    environment_key text NOT NULL DEFAULT '',
    origin_status text NOT NULL DEFAULT 'active',
    activated_at_ts_ms bigint,
    retired_at_ts_ms bigint,
    origin_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL DEFAULT (floor(extract(epoch from clock_timestamp()) * 1000))::bigint,
    updated_at_ts_ms bigint NOT NULL DEFAULT (floor(extract(epoch from clock_timestamp()) * 1000))::bigint,
    CONSTRAINT stephen_dcx_channel_origins_channel_check
        CHECK (channel_type IN ('whatsapp', 'telegram', 'wechat')),
    CONSTRAINT stephen_dcx_channel_origins_status_check
        CHECK (origin_status IN ('active', 'retired'))
);

CREATE UNIQUE INDEX IF NOT EXISTS stephen_dcx_channel_origins_provider_sender_key
ON public.stephen_dcx_channel_origins (
    channel_type,
    provider_type,
    provider_sender_id,
    environment_key
);

CREATE INDEX IF NOT EXISTS stephen_dcx_channel_origins_active_lookup_idx
ON public.stephen_dcx_channel_origins (
    channel_type,
    provider_type,
    environment_key,
    origin_status
);

CREATE TABLE IF NOT EXISTS public.stephen_dcx_contact_method_channel_confirmations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.stephen_dcx_users(id) ON DELETE CASCADE,
    contact_method_id bigint NOT NULL REFERENCES public.stephen_dcx_users_contact_methods(id) ON DELETE CASCADE,
    channel_origin_id bigint NOT NULL REFERENCES public.stephen_dcx_channel_origins(id) ON DELETE RESTRICT,
    auth_challenge_id bigint REFERENCES public.stephen_dcx_user_auth_challenges(id) ON DELETE SET NULL,
    confirmation_purpose text NOT NULL DEFAULT 'contact_verification',
    confirmation_status text NOT NULL DEFAULT 'pending',
    provider_message_id text,
    template_name text NOT NULL DEFAULT '',
    template_language_code text NOT NULL DEFAULT '',
    sent_at_ts_ms bigint,
    confirmed_at_ts_ms bigint,
    expires_at_ts_ms bigint,
    confirmation_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL DEFAULT (floor(extract(epoch from clock_timestamp()) * 1000))::bigint,
    updated_at_ts_ms bigint NOT NULL DEFAULT (floor(extract(epoch from clock_timestamp()) * 1000))::bigint,
    CONSTRAINT stephen_dcx_contact_method_channel_confirmations_purpose_check
        CHECK (confirmation_purpose IN ('contact_verification', 'sender_reconfirmation')),
    CONSTRAINT stephen_dcx_contact_method_channel_confirmations_status_check
        CHECK (confirmation_status IN ('pending', 'sent', 'confirmed', 'expired', 'failed', 'invalidated'))
);

CREATE INDEX IF NOT EXISTS stephen_dcx_contact_method_channel_confirmations_user_idx
ON public.stephen_dcx_contact_method_channel_confirmations(user_id, created_at_ts_ms);

CREATE INDEX IF NOT EXISTS stephen_dcx_contact_method_channel_confirmations_contact_origin_idx
ON public.stephen_dcx_contact_method_channel_confirmations(
    contact_method_id,
    channel_origin_id,
    confirmation_status,
    confirmed_at_ts_ms
);

CREATE INDEX IF NOT EXISTS stephen_dcx_contact_method_channel_confirmations_challenge_idx
ON public.stephen_dcx_contact_method_channel_confirmations(auth_challenge_id)
WHERE auth_challenge_id IS NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'stephen_dcx_channel_origins_set_updated_at_ts_ms'
    ) THEN
        CREATE TRIGGER stephen_dcx_channel_origins_set_updated_at_ts_ms
        BEFORE UPDATE ON public.stephen_dcx_channel_origins
        FOR EACH ROW
        EXECUTE FUNCTION public.stephen_dcx_set_updated_at_ts_ms();
    END IF;

    IF EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'stephen_dcx_contact_method_channel_confirmations_set_updated_at'
    )
    AND NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'stephen_dcx_cm_channel_conf_set_updated_at'
    ) THEN
        ALTER TRIGGER stephen_dcx_contact_method_channel_confirmations_set_updated_at
        ON public.stephen_dcx_contact_method_channel_confirmations
        RENAME TO stephen_dcx_cm_channel_conf_set_updated_at;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'stephen_dcx_cm_channel_conf_set_updated_at'
    ) THEN
        CREATE TRIGGER stephen_dcx_cm_channel_conf_set_updated_at
        BEFORE UPDATE ON public.stephen_dcx_contact_method_channel_confirmations
        FOR EACH ROW
        EXECUTE FUNCTION public.stephen_dcx_set_updated_at_ts_ms();
    END IF;
END $$;
