-- DCX MVP trade interest alerts.
-- Run after trade visibility/publication and cross-surface notification migrations.
--
-- This patch lets a trader choose simple commodity/material interests in Settings.
-- Confirmed, published trades can then notify other verified users whose interests overlap.

CREATE TABLE IF NOT EXISTS public.stephen_dcx_trade_interest_material_options (
    material_key text PRIMARY KEY,
    display_label text NOT NULL,
    synonyms_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    sort_order integer NOT NULL DEFAULT 1000,
    is_active boolean NOT NULL DEFAULT true,
    created_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    updated_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint)
);

INSERT INTO public.stephen_dcx_trade_interest_material_options (
    material_key,
    display_label,
    synonyms_json,
    sort_order,
    is_active
)
VALUES
    ('aluminum', 'Aluminum', '["aluminium", "aluminum", "primary aluminum", "primary aluminium", "aluminum ingot", "aluminium ingot", "p1020a"]'::jsonb, 10, true),
    ('wheat', 'Wheat', '["wheat", "milling wheat", "feed wheat", "durum"]'::jsonb, 20, true),
    ('urea', 'Urea', '["urea", "fertilizer urea", "fertiliser urea", "prilled urea", "granular urea"]'::jsonb, 30, true),
    ('copper', 'Copper', '["copper", "copper cathode", "copper concentrate"]'::jsonb, 40, true),
    ('livestock', 'Livestock', '["livestock", "cattle", "cow", "cows", "calves", "dairy cattle"]'::jsonb, 50, true),
    ('crude_oil', 'Crude oil', '["crude", "crude oil", "brent", "wti"]'::jsonb, 60, true),
    ('lng', 'LNG', '["lng", "liquefied natural gas", "natural gas"]'::jsonb, 70, true),
    ('sugar', 'Sugar', '["sugar", "raw sugar", "white sugar", "icumsa"]'::jsonb, 80, true),
    ('coffee', 'Coffee', '["coffee", "arabica", "robusta"]'::jsonb, 90, true),
    ('soybeans', 'Soybeans', '["soybean", "soybeans", "soya", "soy meal", "soybean meal"]'::jsonb, 100, true)
ON CONFLICT (material_key)
DO UPDATE
SET
    display_label = EXCLUDED.display_label,
    synonyms_json = EXCLUDED.synonyms_json,
    sort_order = EXCLUDED.sort_order,
    is_active = EXCLUDED.is_active,
    updated_at_ts_ms = ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint);

CREATE TABLE IF NOT EXISTS public.stephen_dcx_user_trade_interest_materials (
    user_id bigint NOT NULL REFERENCES public.stephen_dcx_users(id) ON DELETE CASCADE,
    material_key text NOT NULL REFERENCES public.stephen_dcx_trade_interest_material_options(material_key) ON DELETE CASCADE,
    created_at_ts_ms bigint NOT NULL,
    PRIMARY KEY (user_id, material_key)
);

CREATE INDEX IF NOT EXISTS stephen_dcx_user_trade_interest_materials_material_idx
ON public.stephen_dcx_user_trade_interest_materials(material_key, user_id);

CREATE TABLE IF NOT EXISTS public.stephen_dcx_trade_interest_alert_deliveries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_id bigint NOT NULL REFERENCES public.stephen_dcx_trades(id) ON DELETE CASCADE,
    trade_publication_id bigint NULL REFERENCES public.stephen_dcx_trade_publications(id) ON DELETE SET NULL,
    recipient_user_id bigint NOT NULL REFERENCES public.stephen_dcx_users(id) ON DELETE CASCADE,
    material_key text NOT NULL REFERENCES public.stephen_dcx_trade_interest_material_options(material_key) ON DELETE CASCADE,
    channel_type text NOT NULL DEFAULT 'app_only',
    delivery_status text NOT NULL DEFAULT 'pending',
    provider_type text,
    provider_message_id text,
    delivery_error text NOT NULL DEFAULT '',
    delivery_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL,
    updated_at_ts_ms bigint NOT NULL,
    CONSTRAINT stephen_dcx_trade_interest_alert_deliveries_unique_recipient_material
        UNIQUE (trade_id, recipient_user_id, material_key)
);

CREATE INDEX IF NOT EXISTS stephen_dcx_trade_interest_alert_deliveries_recipient_idx
ON public.stephen_dcx_trade_interest_alert_deliveries(recipient_user_id, created_at_ts_ms DESC, id DESC);

CREATE INDEX IF NOT EXISTS stephen_dcx_trade_interest_alert_deliveries_trade_idx
ON public.stephen_dcx_trade_interest_alert_deliveries(trade_id, created_at_ts_ms DESC, id DESC);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'stephen_dcx_trade_interest_alert_deliveries_channel_check'
    ) THEN
        ALTER TABLE public.stephen_dcx_trade_interest_alert_deliveries
        ADD CONSTRAINT stephen_dcx_trade_interest_alert_deliveries_channel_check
        CHECK (channel_type IN ('app_only', 'email', 'whatsapp'));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'stephen_dcx_trade_interest_alert_deliveries_status_check'
    ) THEN
        ALTER TABLE public.stephen_dcx_trade_interest_alert_deliveries
        ADD CONSTRAINT stephen_dcx_trade_interest_alert_deliveries_status_check
        CHECK (delivery_status IN ('pending', 'sent', 'skipped', 'failed'));
    END IF;
END $$;
