-- CONTEXT:
-- Adds the small social action layer behind the DCX Network feed: likes,
-- reposts, bookmarks, and per-user post views. These tables intentionally
-- keep actions separate from posts so counts and user state stay simple.

BEGIN;

CREATE TABLE IF NOT EXISTS public.stephen_dcx_network_feed_likes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_post_id bigint NOT NULL REFERENCES public.stephen_dcx_network_feed_posts(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES public.stephen_dcx_users(id) ON DELETE CASCADE,
    like_status text NOT NULL DEFAULT 'active',
    like_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    updated_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    CONSTRAINT stephen_dcx_network_feed_likes_status_check CHECK (like_status IN ('active', 'inactive')),
    CONSTRAINT stephen_dcx_network_feed_likes_post_user_key UNIQUE (feed_post_id, user_id)
);

CREATE INDEX IF NOT EXISTS stephen_dcx_network_feed_likes_post_active_idx
ON public.stephen_dcx_network_feed_likes(feed_post_id, like_status, updated_at_ts_ms DESC, id DESC);

CREATE INDEX IF NOT EXISTS stephen_dcx_network_feed_likes_user_active_idx
ON public.stephen_dcx_network_feed_likes(user_id, like_status, updated_at_ts_ms DESC, id DESC);

CREATE TABLE IF NOT EXISTS public.stephen_dcx_network_feed_reposts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_post_id bigint NOT NULL REFERENCES public.stephen_dcx_network_feed_posts(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES public.stephen_dcx_users(id) ON DELETE CASCADE,
    repost_status text NOT NULL DEFAULT 'active',
    repost_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    updated_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    CONSTRAINT stephen_dcx_network_feed_reposts_status_check CHECK (repost_status IN ('active', 'inactive')),
    CONSTRAINT stephen_dcx_network_feed_reposts_post_user_key UNIQUE (feed_post_id, user_id)
);

CREATE INDEX IF NOT EXISTS stephen_dcx_network_feed_reposts_post_active_idx
ON public.stephen_dcx_network_feed_reposts(feed_post_id, repost_status, updated_at_ts_ms DESC, id DESC);

CREATE INDEX IF NOT EXISTS stephen_dcx_network_feed_reposts_user_active_idx
ON public.stephen_dcx_network_feed_reposts(user_id, repost_status, updated_at_ts_ms DESC, id DESC);

CREATE TABLE IF NOT EXISTS public.stephen_dcx_network_feed_bookmarks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_post_id bigint NOT NULL REFERENCES public.stephen_dcx_network_feed_posts(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES public.stephen_dcx_users(id) ON DELETE CASCADE,
    bookmark_status text NOT NULL DEFAULT 'active',
    bookmark_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    updated_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    CONSTRAINT stephen_dcx_network_feed_bookmarks_status_check CHECK (bookmark_status IN ('active', 'inactive')),
    CONSTRAINT stephen_dcx_network_feed_bookmarks_post_user_key UNIQUE (feed_post_id, user_id)
);

CREATE INDEX IF NOT EXISTS stephen_dcx_network_feed_bookmarks_post_active_idx
ON public.stephen_dcx_network_feed_bookmarks(feed_post_id, bookmark_status, updated_at_ts_ms DESC, id DESC);

CREATE INDEX IF NOT EXISTS stephen_dcx_network_feed_bookmarks_user_active_idx
ON public.stephen_dcx_network_feed_bookmarks(user_id, bookmark_status, updated_at_ts_ms DESC, id DESC);

CREATE TABLE IF NOT EXISTS public.stephen_dcx_network_feed_views (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_post_id bigint NOT NULL REFERENCES public.stephen_dcx_network_feed_posts(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES public.stephen_dcx_users(id) ON DELETE CASCADE,
    view_count bigint NOT NULL DEFAULT 1,
    first_viewed_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    last_viewed_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    view_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    updated_at_ts_ms bigint NOT NULL DEFAULT ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint),
    CONSTRAINT stephen_dcx_network_feed_views_count_check CHECK (view_count >= 1),
    CONSTRAINT stephen_dcx_network_feed_views_post_user_key UNIQUE (feed_post_id, user_id)
);

CREATE INDEX IF NOT EXISTS stephen_dcx_network_feed_views_post_idx
ON public.stephen_dcx_network_feed_views(feed_post_id, updated_at_ts_ms DESC, id DESC);

CREATE INDEX IF NOT EXISTS stephen_dcx_network_feed_views_user_idx
ON public.stephen_dcx_network_feed_views(user_id, updated_at_ts_ms DESC, id DESC);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'stephen_dcx_network_feed_likes_set_updated_at_ts_ms'
    ) THEN
        CREATE TRIGGER stephen_dcx_network_feed_likes_set_updated_at_ts_ms
        BEFORE UPDATE ON public.stephen_dcx_network_feed_likes
        FOR EACH ROW
        EXECUTE FUNCTION public.stephen_dcx_set_updated_at_ts_ms();
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'stephen_dcx_network_feed_reposts_set_updated_at_ts_ms'
    ) THEN
        CREATE TRIGGER stephen_dcx_network_feed_reposts_set_updated_at_ts_ms
        BEFORE UPDATE ON public.stephen_dcx_network_feed_reposts
        FOR EACH ROW
        EXECUTE FUNCTION public.stephen_dcx_set_updated_at_ts_ms();
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'stephen_dcx_network_feed_bookmarks_set_updated_at_ts_ms'
    ) THEN
        CREATE TRIGGER stephen_dcx_network_feed_bookmarks_set_updated_at_ts_ms
        BEFORE UPDATE ON public.stephen_dcx_network_feed_bookmarks
        FOR EACH ROW
        EXECUTE FUNCTION public.stephen_dcx_set_updated_at_ts_ms();
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'stephen_dcx_network_feed_views_set_updated_at_ts_ms'
    ) THEN
        CREATE TRIGGER stephen_dcx_network_feed_views_set_updated_at_ts_ms
        BEFORE UPDATE ON public.stephen_dcx_network_feed_views
        FOR EACH ROW
        EXECUTE FUNCTION public.stephen_dcx_set_updated_at_ts_ms();
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_roles
        WHERE rolname = 'dcxagent_user'
    ) THEN
        GRANT SELECT, INSERT, UPDATE, DELETE
        ON TABLE
            public.stephen_dcx_network_feed_likes,
            public.stephen_dcx_network_feed_reposts,
            public.stephen_dcx_network_feed_bookmarks,
            public.stephen_dcx_network_feed_views
        TO dcxagent_user;

        GRANT USAGE, SELECT
        ON SEQUENCE
            public.stephen_dcx_network_feed_likes_id_seq,
            public.stephen_dcx_network_feed_reposts_id_seq,
            public.stephen_dcx_network_feed_bookmarks_id_seq,
            public.stephen_dcx_network_feed_views_id_seq
        TO dcxagent_user;
    END IF;
END $$;

COMMIT;
