-- CONTEXT:
-- Seeds the multilingual UX-string rows for the authenticated DCX app surfaces.
-- It exists so app auth routes and the authenticated account page can render through the
-- shared `stephen_dcx_ux_strings` model in English, Spanish, French, and German.
--
-- FLOW/SYSTEM:
-- - `app_auth_common`
-- - `app_auth_login_page`
-- - `app_auth_password_reset_request_page`
-- - `app_auth_password_set_page`
-- - `app_account_page`
--
-- CONTRACT:
-- - Safe to rerun.
-- - Inserts missing English live originals only.
-- - Inserts missing live translations only.
-- - Does not delete or overwrite existing live rows.

WITH desired_english_originals(string_group, string_key, text_value) AS (
    VALUES
        ('app_auth_common', 'checking_session', $$Checking DCX session...$$),

        ('app_auth_login_page', 'surface_label', $$DCX App$$),
        ('app_auth_login_page', 'page_title', $$Sign in$$),
        ('app_auth_login_page', 'hero_eyebrow', $$Account access$$),
        ('app_auth_login_page', 'hero_title', $$Continue into the private DCX app.$$),
        ('app_auth_login_page', 'hero_body', $$Use the same shared DCX session for both the app and internal admin surfaces.$$),
        ('app_auth_login_page', 'auth_eyebrow', $$Shared auth$$),
        ('app_auth_login_page', 'auth_title', $$Email and password$$),
        ('app_auth_login_page', 'auth_body', $$Confirmed users with a password can enter the app immediately. Admin access stays role-gated on top of the same browser session.$$),
        ('app_auth_login_page', 'field_email', $$Email$$),
        ('app_auth_login_page', 'field_email_placeholder', $$you@company.com$$),
        ('app_auth_login_page', 'field_password', $$Password$$),
        ('app_auth_login_page', 'field_password_placeholder', $$Enter your password$$),
        ('app_auth_login_page', 'help_idle', $$Use your confirmed email and current password. If you lost access, request a new password link.$$),
        ('app_auth_login_page', 'submit_idle', $$Sign in$$),
        ('app_auth_login_page', 'submit_pending', $$Signing in...$$),
        ('app_auth_login_page', 'forgot_password_button', $$Forgot password?$$),

        ('app_auth_password_reset_request_page', 'surface_label', $$DCX App$$),
        ('app_auth_password_reset_request_page', 'page_title', $$Reset password$$),
        ('app_auth_password_reset_request_page', 'hero_eyebrow', $$Recovery$$),
        ('app_auth_password_reset_request_page', 'hero_title', $$Send a secure password link to your confirmed email.$$),
        ('app_auth_password_reset_request_page', 'hero_body', $$If the account exists and is already confirmed, DCX will send a one-time password link to the email address you enter here.$$),
        ('app_auth_password_reset_request_page', 'auth_eyebrow', $$Shared auth$$),
        ('app_auth_password_reset_request_page', 'auth_title', $$Password reset email$$),
        ('app_auth_password_reset_request_page', 'auth_body', $$The response stays generic for security. Use the newest email link only once.$$),
        ('app_auth_password_reset_request_page', 'field_email', $$Email$$),
        ('app_auth_password_reset_request_page', 'field_email_placeholder', $$you@company.com$$),
        ('app_auth_password_reset_request_page', 'help_idle', $$We will send a one-time link to the confirmed account email if it exists.$$),
        ('app_auth_password_reset_request_page', 'success_message', $$If that email belongs to a confirmed DCX account, a secure password link is on the way.$$),
        ('app_auth_password_reset_request_page', 'submit_idle', $$Send password link$$),
        ('app_auth_password_reset_request_page', 'submit_pending', $$Sending...$$),
        ('app_auth_password_reset_request_page', 'back_to_login_button', $$Back to sign in$$),

        ('app_auth_password_set_page', 'surface_label', $$DCX App$$),
        ('app_auth_password_set_page', 'page_title', $$Password$$),
        ('app_auth_password_set_page', 'hero_eyebrow', $$Shared auth$$),
        ('app_auth_password_set_page', 'hero_title_setup', $$Create your DCX password.$$),
        ('app_auth_password_set_page', 'hero_body_setup', $$Your email is now verified. Choose the password you will use to enter the private DCX app.$$),
        ('app_auth_password_set_page', 'hero_title_reset', $$Choose a new password.$$),
        ('app_auth_password_set_page', 'hero_body_reset', $$Use the secure link token from your reset email to choose a new password, then sign in again.$$),
        ('app_auth_password_set_page', 'rule_eyebrow', $$Password rule$$),
        ('app_auth_password_set_page', 'rule_title', $$At least 12 characters$$),
        ('app_auth_password_set_page', 'rule_body', $$Longer passphrases are welcome. Once saved, return to sign in with the new password.$$),
        ('app_auth_password_set_page', 'field_password', $$New password$$),
        ('app_auth_password_set_page', 'field_password_placeholder', $$Enter a strong passphrase$$),
        ('app_auth_password_set_page', 'field_confirm_password', $$Confirm password$$),
        ('app_auth_password_set_page', 'field_confirm_password_placeholder', $$Enter the same password again$$),
        ('app_auth_password_set_page', 'validation_min_length', $$Use a password with at least 12 characters.$$),
        ('app_auth_password_set_page', 'validation_confirmation_mismatch', $$The password confirmation must match exactly.$$),
        ('app_auth_password_set_page', 'token_missing_error', $$This password link is missing or has already been cleared. Request a fresh one and retry.$$),
        ('app_auth_password_set_page', 'help_idle', $$This one-time link works only once. If it expires, request another password email.$$),
        ('app_auth_password_set_page', 'success_message', $$Password saved. Continue back to sign in.$$),
        ('app_auth_password_set_page', 'submit_idle', $$Save password$$),
        ('app_auth_password_set_page', 'submit_pending', $$Saving...$$),
        ('app_auth_password_set_page', 'back_to_login_button', $$Back to sign in$$),

        ('app_account_page', 'surface_label', $$DCX App$$),
        ('app_account_page', 'page_title', $$Account$$),
        ('app_account_page', 'inline_autosave_badge', $$Inline autosave MVP surface$$),
        ('app_account_page', 'local_debug_user_label_prefix', $$Local debug user:$$),
        ('app_account_page', 'refresh_button_label', $$Refresh$$),
        ('app_account_page', 'loading_account_summary', $$Loading account summary...$$),
        ('app_account_page', 'error_account_read_blocked', $$Account read blocked$$),
        ('app_account_page', 'error_account_load_title', $$We could not load the DCX account summary.$$),
        ('app_account_page', 'identity_eyebrow', $$Identity$$),
        ('app_account_page', 'identity_subtitle', $$Confirmed account with stable DCX user identity.$$),
        ('app_account_page', 'account_state_confirmed', $$Confirmed$$),
        ('app_account_page', 'account_state_pending', $$Pending$$),
        ('app_account_page', 'field_primary_email', $$Primary email$$),
        ('app_account_page', 'field_primary_phone', $$Primary phone$$),
        ('app_account_page', 'field_user_uuid', $$User UUID$$),
        ('app_account_page', 'field_account_status', $$Account status$$),
        ('app_account_page', 'field_preferred_language', $$Preferred language$$),
        ('app_account_page', 'field_timezone', $$Timezone$$),
        ('app_account_page', 'field_email_preference', $$Email preference$$),
        ('app_account_page', 'field_email_confirmed_at', $$Email confirmed at$$),
        ('app_account_page', 'field_phone_confirmed_at', $$Phone confirmed at$$),
        ('app_account_page', 'field_last_seen_at', $$Last seen at$$),
        ('app_account_page', 'field_created_at', $$Created at$$),
        ('app_account_page', 'field_updated_at', $$Updated at$$),
        ('app_account_page', 'field_not_set', $$Not set$$),
        ('app_account_page', 'field_phone_not_set_yet', $$Not set yet$$),
        ('app_account_page', 'logout_button_pending_label', $$Signing out...$$),
        ('app_account_page', 'logout_button_label', $$Logout$$),
        ('app_account_page', 'editable_status_idle', $$Blue means editable. Click to adjust.$$),
        ('app_account_page', 'editable_status_editing', $$Editing. Choose a value to autosave.$$),
        ('app_account_page', 'editable_status_saving', $$Saving...$$),
        ('app_account_page', 'editable_status_saved', $$Saved.$$),
        ('app_account_page', 'editable_status_retrying_template', $$Retrying save ({attempt}/{total})...$$),
        ('app_account_page', 'editable_status_save_failed', $$Save failed. Please click back in and retry.$$),
        ('app_account_page', 'editable_status_saving_default_language', $$Saving default language...$$),
        ('app_account_page', 'error_account_load_suggested_action', $$Sign in again through the DCX app login flow, then retry.$$),
        ('app_account_page', 'activity_eyebrow', $$Activity$$),
        ('app_account_page', 'activity_title', $$Account timeline$$),
        ('app_account_page', 'email_preference_announcements', $$Announcements$$),
        ('app_account_page', 'email_preference_essential_only', $$Essential only$$),
        ('app_account_page', 'next_eyebrow', $$Next$$),
        ('app_account_page', 'next_title', $$Email and phone changes can come after the field behavior is proven.$$),
        ('app_account_page', 'next_body', $$This pass intentionally keeps primary email and phone read-only. Preferred language, timezone, and communication preference now prove the inline autosave behavior, retry path, and save-state feedback we can reuse later for higher-risk account changes.$$)
),
english_language AS (
    SELECT id
    FROM stephen_dcx_languages
    WHERE language_code = 'en'
    LIMIT 1
)
INSERT INTO stephen_dcx_ux_strings
(string_group, string_key, language_id, text, is_original, is_live, version_of_id, translation_of_id)
SELECT
    desired_english_originals.string_group,
    desired_english_originals.string_key,
    english_language.id,
    desired_english_originals.text_value,
    TRUE,
    TRUE,
    NULL,
    NULL
FROM desired_english_originals
CROSS JOIN english_language
WHERE NOT EXISTS (
    SELECT 1
    FROM stephen_dcx_ux_strings existing
    WHERE existing.string_group = desired_english_originals.string_group
      AND existing.string_key = desired_english_originals.string_key
      AND existing.language_id = english_language.id
      AND existing.is_original = TRUE
      AND existing.is_live = TRUE
);

WITH desired_translations(string_group, string_key, language_code, text_value) AS (
    VALUES
        ('app_auth_common', 'checking_session', 'es', $$Comprobando la sesión de DCX...$$),
        ('app_auth_common', 'checking_session', 'fr', $$Vérification de la session DCX...$$),
        ('app_auth_common', 'checking_session', 'de', $$DCX-Sitzung wird geprüft...$$),

        ('app_auth_login_page', 'surface_label', 'es', $$DCX App$$),
        ('app_auth_login_page', 'surface_label', 'fr', $$DCX App$$),
        ('app_auth_login_page', 'surface_label', 'de', $$DCX App$$),
        ('app_auth_login_page', 'page_title', 'es', $$Iniciar sesión$$),
        ('app_auth_login_page', 'page_title', 'fr', $$Connexion$$),
        ('app_auth_login_page', 'page_title', 'de', $$Anmelden$$),
        ('app_auth_login_page', 'hero_eyebrow', 'es', $$Acceso a la cuenta$$),
        ('app_auth_login_page', 'hero_eyebrow', 'fr', $$Accès au compte$$),
        ('app_auth_login_page', 'hero_eyebrow', 'de', $$Kontozugang$$),
        ('app_auth_login_page', 'hero_title', 'es', $$Continúa hacia la app privada de DCX.$$),
        ('app_auth_login_page', 'hero_title', 'fr', $$Continuez vers l'application privée DCX.$$),
        ('app_auth_login_page', 'hero_title', 'de', $$Weiter zur privaten DCX-App.$$),
        ('app_auth_login_page', 'hero_body', 'es', $$Usa la misma sesión compartida de DCX para la app y las superficies internas de admin.$$),
        ('app_auth_login_page', 'hero_body', 'fr', $$Utilisez la même session DCX partagée pour l'application et les surfaces internes d'administration.$$),
        ('app_auth_login_page', 'hero_body', 'de', $$Verwenden Sie dieselbe gemeinsame DCX-Sitzung für die App und die internen Admin-Oberflächen.$$),
        ('app_auth_login_page', 'auth_eyebrow', 'es', $$Auth compartida$$),
        ('app_auth_login_page', 'auth_eyebrow', 'fr', $$Auth partagée$$),
        ('app_auth_login_page', 'auth_eyebrow', 'de', $$Geteilte Auth$$),
        ('app_auth_login_page', 'auth_title', 'es', $$Correo y contraseña$$),
        ('app_auth_login_page', 'auth_title', 'fr', $$E-mail et mot de passe$$),
        ('app_auth_login_page', 'auth_title', 'de', $$E-Mail und Passwort$$),
        ('app_auth_login_page', 'auth_body', 'es', $$Los usuarios confirmados con contraseña pueden entrar en la app de inmediato. El acceso admin sigue controlado por rol sobre la misma sesión del navegador.$$),
        ('app_auth_login_page', 'auth_body', 'fr', $$Les utilisateurs confirmés avec un mot de passe peuvent entrer immédiatement dans l'application. L'accès admin reste contrôlé par rôle au-dessus de la même session navigateur.$$),
        ('app_auth_login_page', 'auth_body', 'de', $$Bestätigte Benutzer mit Passwort können sofort in die App. Der Admin-Zugang bleibt zusätzlich über die Rolle in derselben Browser-Sitzung gesteuert.$$),
        ('app_auth_login_page', 'field_email', 'es', $$Correo electrónico$$),
        ('app_auth_login_page', 'field_email', 'fr', $$E-mail$$),
        ('app_auth_login_page', 'field_email', 'de', $$E-Mail$$),
        ('app_auth_login_page', 'field_email_placeholder', 'es', $$tu@empresa.com$$),
        ('app_auth_login_page', 'field_email_placeholder', 'fr', $$vous@entreprise.com$$),
        ('app_auth_login_page', 'field_email_placeholder', 'de', $$sie@firma.com$$),
        ('app_auth_login_page', 'field_password', 'es', $$Contraseña$$),
        ('app_auth_login_page', 'field_password', 'fr', $$Mot de passe$$),
        ('app_auth_login_page', 'field_password', 'de', $$Passwort$$),
        ('app_auth_login_page', 'field_password_placeholder', 'es', $$Introduce tu contraseña$$),
        ('app_auth_login_page', 'field_password_placeholder', 'fr', $$Entrez votre mot de passe$$),
        ('app_auth_login_page', 'field_password_placeholder', 'de', $$Geben Sie Ihr Passwort ein$$),
        ('app_auth_login_page', 'help_idle', 'es', $$Usa tu correo confirmado y tu contraseña actual. Si perdiste el acceso, solicita un nuevo enlace de contraseña.$$),
        ('app_auth_login_page', 'help_idle', 'fr', $$Utilisez votre e-mail confirmé et votre mot de passe actuel. Si vous avez perdu l'accès, demandez un nouveau lien de mot de passe.$$),
        ('app_auth_login_page', 'help_idle', 'de', $$Verwenden Sie Ihre bestätigte E-Mail und Ihr aktuelles Passwort. Wenn Sie den Zugang verloren haben, fordern Sie einen neuen Passwort-Link an.$$),
        ('app_auth_login_page', 'submit_idle', 'es', $$Iniciar sesión$$),
        ('app_auth_login_page', 'submit_idle', 'fr', $$Se connecter$$),
        ('app_auth_login_page', 'submit_idle', 'de', $$Anmelden$$),
        ('app_auth_login_page', 'submit_pending', 'es', $$Iniciando sesión...$$),
        ('app_auth_login_page', 'submit_pending', 'fr', $$Connexion en cours...$$),
        ('app_auth_login_page', 'submit_pending', 'de', $$Anmeldung läuft...$$),
        ('app_auth_login_page', 'forgot_password_button', 'es', $$¿Has olvidado tu contraseña?$$),
        ('app_auth_login_page', 'forgot_password_button', 'fr', $$Mot de passe oublié ?$$),
        ('app_auth_login_page', 'forgot_password_button', 'de', $$Passwort vergessen?$$),

        ('app_auth_password_reset_request_page', 'surface_label', 'es', $$DCX App$$),
        ('app_auth_password_reset_request_page', 'surface_label', 'fr', $$DCX App$$),
        ('app_auth_password_reset_request_page', 'surface_label', 'de', $$DCX App$$),
        ('app_auth_password_reset_request_page', 'page_title', 'es', $$Restablecer contraseña$$),
        ('app_auth_password_reset_request_page', 'page_title', 'fr', $$Réinitialiser le mot de passe$$),
        ('app_auth_password_reset_request_page', 'page_title', 'de', $$Passwort zurücksetzen$$),
        ('app_auth_password_reset_request_page', 'hero_eyebrow', 'es', $$Recuperación$$),
        ('app_auth_password_reset_request_page', 'hero_eyebrow', 'fr', $$Récupération$$),
        ('app_auth_password_reset_request_page', 'hero_eyebrow', 'de', $$Wiederherstellung$$),
        ('app_auth_password_reset_request_page', 'hero_title', 'es', $$Envía un enlace seguro de contraseña a tu correo confirmado.$$),
        ('app_auth_password_reset_request_page', 'hero_title', 'fr', $$Envoyez un lien de mot de passe sécurisé à votre e-mail confirmé.$$),
        ('app_auth_password_reset_request_page', 'hero_title', 'de', $$Senden Sie einen sicheren Passwort-Link an Ihre bestätigte E-Mail.$$),
        ('app_auth_password_reset_request_page', 'hero_body', 'es', $$Si la cuenta existe y ya está confirmada, DCX enviará un enlace de contraseña de un solo uso al correo que introduzcas aquí.$$),
        ('app_auth_password_reset_request_page', 'hero_body', 'fr', $$Si le compte existe et est déjà confirmé, DCX enverra un lien de mot de passe à usage unique à l'adresse e-mail que vous saisissez ici.$$),
        ('app_auth_password_reset_request_page', 'hero_body', 'de', $$Wenn das Konto existiert und bereits bestätigt ist, sendet DCX einen einmaligen Passwort-Link an die hier eingegebene E-Mail-Adresse.$$),
        ('app_auth_password_reset_request_page', 'auth_eyebrow', 'es', $$Auth compartida$$),
        ('app_auth_password_reset_request_page', 'auth_eyebrow', 'fr', $$Auth partagée$$),
        ('app_auth_password_reset_request_page', 'auth_eyebrow', 'de', $$Geteilte Auth$$),
        ('app_auth_password_reset_request_page', 'auth_title', 'es', $$Correo de restablecimiento de contraseña$$),
        ('app_auth_password_reset_request_page', 'auth_title', 'fr', $$E-mail de réinitialisation du mot de passe$$),
        ('app_auth_password_reset_request_page', 'auth_title', 'de', $$E-Mail zum Zurücksetzen des Passworts$$),
        ('app_auth_password_reset_request_page', 'auth_body', 'es', $$La respuesta se mantiene genérica por seguridad. Usa solo el enlace del correo más reciente.$$),
        ('app_auth_password_reset_request_page', 'auth_body', 'fr', $$La réponse reste générique pour des raisons de sécurité. Utilisez uniquement le lien du dernier e-mail.$$),
        ('app_auth_password_reset_request_page', 'auth_body', 'de', $$Die Antwort bleibt aus Sicherheitsgründen allgemein. Verwenden Sie nur den Link aus der neuesten E-Mail.$$),
        ('app_auth_password_reset_request_page', 'field_email', 'es', $$Correo electrónico$$),
        ('app_auth_password_reset_request_page', 'field_email', 'fr', $$E-mail$$),
        ('app_auth_password_reset_request_page', 'field_email', 'de', $$E-Mail$$),
        ('app_auth_password_reset_request_page', 'field_email_placeholder', 'es', $$tu@empresa.com$$),
        ('app_auth_password_reset_request_page', 'field_email_placeholder', 'fr', $$vous@entreprise.com$$),
        ('app_auth_password_reset_request_page', 'field_email_placeholder', 'de', $$sie@firma.com$$),
        ('app_auth_password_reset_request_page', 'help_idle', 'es', $$Enviaremos un enlace de un solo uso al correo confirmado de la cuenta si existe.$$),
        ('app_auth_password_reset_request_page', 'help_idle', 'fr', $$Nous enverrons un lien à usage unique à l'e-mail confirmé du compte s'il existe.$$),
        ('app_auth_password_reset_request_page', 'help_idle', 'de', $$Wir senden einen einmaligen Link an die bestätigte Konto-E-Mail, falls das Konto existiert.$$),
        ('app_auth_password_reset_request_page', 'success_message', 'es', $$Si ese correo pertenece a una cuenta DCX confirmada, ya va de camino un enlace seguro de contraseña.$$),
        ('app_auth_password_reset_request_page', 'success_message', 'fr', $$Si cet e-mail appartient à un compte DCX confirmé, un lien de mot de passe sécurisé est en route.$$),
        ('app_auth_password_reset_request_page', 'success_message', 'de', $$Wenn diese E-Mail zu einem bestätigten DCX-Konto gehört, ist ein sicherer Passwort-Link bereits unterwegs.$$),
        ('app_auth_password_reset_request_page', 'submit_idle', 'es', $$Enviar enlace de contraseña$$),
        ('app_auth_password_reset_request_page', 'submit_idle', 'fr', $$Envoyer le lien de mot de passe$$),
        ('app_auth_password_reset_request_page', 'submit_idle', 'de', $$Passwort-Link senden$$),
        ('app_auth_password_reset_request_page', 'submit_pending', 'es', $$Enviando...$$),
        ('app_auth_password_reset_request_page', 'submit_pending', 'fr', $$Envoi en cours...$$),
        ('app_auth_password_reset_request_page', 'submit_pending', 'de', $$Wird gesendet...$$),
        ('app_auth_password_reset_request_page', 'back_to_login_button', 'es', $$Volver al inicio de sesión$$),
        ('app_auth_password_reset_request_page', 'back_to_login_button', 'fr', $$Retour à la connexion$$),
        ('app_auth_password_reset_request_page', 'back_to_login_button', 'de', $$Zurück zur Anmeldung$$),

        ('app_auth_password_set_page', 'surface_label', 'es', $$DCX App$$),
        ('app_auth_password_set_page', 'surface_label', 'fr', $$DCX App$$),
        ('app_auth_password_set_page', 'surface_label', 'de', $$DCX App$$),
        ('app_auth_password_set_page', 'page_title', 'es', $$Contraseña$$),
        ('app_auth_password_set_page', 'page_title', 'fr', $$Mot de passe$$),
        ('app_auth_password_set_page', 'page_title', 'de', $$Passwort$$),
        ('app_auth_password_set_page', 'hero_eyebrow', 'es', $$Auth compartida$$),
        ('app_auth_password_set_page', 'hero_eyebrow', 'fr', $$Auth partagée$$),
        ('app_auth_password_set_page', 'hero_eyebrow', 'de', $$Geteilte Auth$$),
        ('app_auth_password_set_page', 'hero_title_setup', 'es', $$Crea tu contraseña de DCX.$$),
        ('app_auth_password_set_page', 'hero_title_setup', 'fr', $$Créez votre mot de passe DCX.$$),
        ('app_auth_password_set_page', 'hero_title_setup', 'de', $$Erstellen Sie Ihr DCX-Passwort.$$),
        ('app_auth_password_set_page', 'hero_body_setup', 'es', $$Tu correo ya está verificado. Elige la contraseña que usarás para entrar en la app privada de DCX.$$),
        ('app_auth_password_set_page', 'hero_body_setup', 'fr', $$Votre e-mail est maintenant vérifié. Choisissez le mot de passe que vous utiliserez pour entrer dans l'application privée DCX.$$),
        ('app_auth_password_set_page', 'hero_body_setup', 'de', $$Ihre E-Mail ist jetzt verifiziert. Wählen Sie das Passwort, mit dem Sie die private DCX-App betreten.$$),
        ('app_auth_password_set_page', 'hero_title_reset', 'es', $$Elige una nueva contraseña.$$),
        ('app_auth_password_set_page', 'hero_title_reset', 'fr', $$Choisissez un nouveau mot de passe.$$),
        ('app_auth_password_set_page', 'hero_title_reset', 'de', $$Wählen Sie ein neues Passwort.$$),
        ('app_auth_password_set_page', 'hero_body_reset', 'es', $$Usa el token seguro del enlace de restablecimiento para elegir una nueva contraseña y después vuelve a iniciar sesión.$$),
        ('app_auth_password_set_page', 'hero_body_reset', 'fr', $$Utilisez le jeton sécurisé du lien de réinitialisation pour choisir un nouveau mot de passe, puis reconnectez-vous.$$),
        ('app_auth_password_set_page', 'hero_body_reset', 'de', $$Verwenden Sie das sichere Token aus Ihrem Reset-Link, um ein neues Passwort zu wählen, und melden Sie sich danach erneut an.$$),
        ('app_auth_password_set_page', 'rule_eyebrow', 'es', $$Regla de contraseña$$),
        ('app_auth_password_set_page', 'rule_eyebrow', 'fr', $$Règle du mot de passe$$),
        ('app_auth_password_set_page', 'rule_eyebrow', 'de', $$Passwortregel$$),
        ('app_auth_password_set_page', 'rule_title', 'es', $$Al menos 12 caracteres$$),
        ('app_auth_password_set_page', 'rule_title', 'fr', $$Au moins 12 caractères$$),
        ('app_auth_password_set_page', 'rule_title', 'de', $$Mindestens 12 Zeichen$$),
        ('app_auth_password_set_page', 'rule_body', 'es', $$Las frases largas son bienvenidas. Una vez guardada, vuelve a iniciar sesión con la nueva contraseña.$$),
        ('app_auth_password_set_page', 'rule_body', 'fr', $$Les phrases de passe plus longues sont les bienvenues. Une fois enregistrée, revenez à la connexion avec le nouveau mot de passe.$$),
        ('app_auth_password_set_page', 'rule_body', 'de', $$Längere Passphrasen sind willkommen. Nach dem Speichern kehren Sie zur Anmeldung mit dem neuen Passwort zurück.$$),
        ('app_auth_password_set_page', 'field_password', 'es', $$Nueva contraseña$$),
        ('app_auth_password_set_page', 'field_password', 'fr', $$Nouveau mot de passe$$),
        ('app_auth_password_set_page', 'field_password', 'de', $$Neues Passwort$$),
        ('app_auth_password_set_page', 'field_password_placeholder', 'es', $$Introduce una frase segura$$),
        ('app_auth_password_set_page', 'field_password_placeholder', 'fr', $$Entrez une phrase de passe robuste$$),
        ('app_auth_password_set_page', 'field_password_placeholder', 'de', $$Geben Sie eine starke Passphrase ein$$),
        ('app_auth_password_set_page', 'field_confirm_password', 'es', $$Confirmar contraseña$$),
        ('app_auth_password_set_page', 'field_confirm_password', 'fr', $$Confirmer le mot de passe$$),
        ('app_auth_password_set_page', 'field_confirm_password', 'de', $$Passwort bestätigen$$),
        ('app_auth_password_set_page', 'field_confirm_password_placeholder', 'es', $$Introduce la misma contraseña otra vez$$),
        ('app_auth_password_set_page', 'field_confirm_password_placeholder', 'fr', $$Entrez à nouveau le même mot de passe$$),
        ('app_auth_password_set_page', 'field_confirm_password_placeholder', 'de', $$Geben Sie dasselbe Passwort erneut ein$$),
        ('app_auth_password_set_page', 'validation_min_length', 'es', $$Usa una contraseña de al menos 12 caracteres.$$),
        ('app_auth_password_set_page', 'validation_min_length', 'fr', $$Utilisez un mot de passe d'au moins 12 caractères.$$),
        ('app_auth_password_set_page', 'validation_min_length', 'de', $$Verwenden Sie ein Passwort mit mindestens 12 Zeichen.$$),
        ('app_auth_password_set_page', 'validation_confirmation_mismatch', 'es', $$La confirmación de la contraseña debe coincidir exactamente.$$),
        ('app_auth_password_set_page', 'validation_confirmation_mismatch', 'fr', $$La confirmation du mot de passe doit correspondre exactement.$$),
        ('app_auth_password_set_page', 'validation_confirmation_mismatch', 'de', $$Die Passwortbestätigung muss exakt übereinstimmen.$$),
        ('app_auth_password_set_page', 'token_missing_error', 'es', $$Falta este enlace de contraseña o ya se ha borrado. Solicita uno nuevo y vuelve a intentarlo.$$),
        ('app_auth_password_set_page', 'token_missing_error', 'fr', $$Ce lien de mot de passe est manquant ou a déjà été effacé. Demandez-en un nouveau et réessayez.$$),
        ('app_auth_password_set_page', 'token_missing_error', 'de', $$Dieser Passwort-Link fehlt oder wurde bereits entfernt. Fordern Sie einen neuen an und versuchen Sie es erneut.$$),
        ('app_auth_password_set_page', 'help_idle', 'es', $$Este enlace de un solo uso funciona solo una vez. Si caduca, solicita otro correo de contraseña.$$),
        ('app_auth_password_set_page', 'help_idle', 'fr', $$Ce lien à usage unique ne fonctionne qu'une seule fois. S'il expire, demandez un autre e-mail de mot de passe.$$),
        ('app_auth_password_set_page', 'help_idle', 'de', $$Dieser Einmal-Link funktioniert nur einmal. Wenn er abläuft, fordern Sie eine weitere Passwort-E-Mail an.$$),
        ('app_auth_password_set_page', 'success_message', 'es', $$Contraseña guardada. Vuelve a iniciar sesión.$$),
        ('app_auth_password_set_page', 'success_message', 'fr', $$Mot de passe enregistré. Revenez à la connexion.$$),
        ('app_auth_password_set_page', 'success_message', 'de', $$Passwort gespeichert. Weiter zurück zur Anmeldung.$$),
        ('app_auth_password_set_page', 'submit_idle', 'es', $$Guardar contraseña$$),
        ('app_auth_password_set_page', 'submit_idle', 'fr', $$Enregistrer le mot de passe$$),
        ('app_auth_password_set_page', 'submit_idle', 'de', $$Passwort speichern$$),
        ('app_auth_password_set_page', 'submit_pending', 'es', $$Guardando...$$),
        ('app_auth_password_set_page', 'submit_pending', 'fr', $$Enregistrement en cours...$$),
        ('app_auth_password_set_page', 'submit_pending', 'de', $$Wird gespeichert...$$),
        ('app_auth_password_set_page', 'back_to_login_button', 'es', $$Volver al inicio de sesión$$),
        ('app_auth_password_set_page', 'back_to_login_button', 'fr', $$Retour à la connexion$$),
        ('app_auth_password_set_page', 'back_to_login_button', 'de', $$Zurück zur Anmeldung$$),

        ('app_account_page', 'surface_label', 'es', $$DCX App$$),
        ('app_account_page', 'surface_label', 'fr', $$DCX App$$),
        ('app_account_page', 'surface_label', 'de', $$DCX App$$),
        ('app_account_page', 'page_title', 'es', $$Cuenta$$),
        ('app_account_page', 'page_title', 'fr', $$Compte$$),
        ('app_account_page', 'page_title', 'de', $$Konto$$),
        ('app_account_page', 'inline_autosave_badge', 'es', $$Superficie MVP con autoguardado en línea$$),
        ('app_account_page', 'inline_autosave_badge', 'fr', $$Surface MVP avec sauvegarde automatique en ligne$$),
        ('app_account_page', 'inline_autosave_badge', 'de', $$MVP-Oberfläche mit Inline-Autospeicherung$$),
        ('app_account_page', 'local_debug_user_label_prefix', 'es', $$Usuario local de depuración:$$),
        ('app_account_page', 'local_debug_user_label_prefix', 'fr', $$Utilisateur local de débogage :$$),
        ('app_account_page', 'local_debug_user_label_prefix', 'de', $$Lokaler Debug-Benutzer:$$),
        ('app_account_page', 'refresh_button_label', 'es', $$Actualizar$$),
        ('app_account_page', 'refresh_button_label', 'fr', $$Actualiser$$),
        ('app_account_page', 'refresh_button_label', 'de', $$Aktualisieren$$),
        ('app_account_page', 'loading_account_summary', 'es', $$Cargando resumen de cuenta...$$),
        ('app_account_page', 'loading_account_summary', 'fr', $$Chargement du résumé du compte...$$),
        ('app_account_page', 'loading_account_summary', 'de', $$Kontozusammenfassung wird geladen...$$),
        ('app_account_page', 'error_account_read_blocked', 'es', $$Lectura de cuenta bloqueada$$),
        ('app_account_page', 'error_account_read_blocked', 'fr', $$Lecture du compte bloquée$$),
        ('app_account_page', 'error_account_read_blocked', 'de', $$Kontolesen blockiert$$),
        ('app_account_page', 'error_account_load_title', 'es', $$No pudimos cargar el resumen de la cuenta de DCX.$$),
        ('app_account_page', 'error_account_load_title', 'fr', $$Nous n'avons pas pu charger le résumé du compte DCX.$$),
        ('app_account_page', 'error_account_load_title', 'de', $$Die DCX-Kontozusammenfassung konnte nicht geladen werden.$$),
        ('app_account_page', 'identity_eyebrow', 'es', $$Identidad$$),
        ('app_account_page', 'identity_eyebrow', 'fr', $$Identité$$),
        ('app_account_page', 'identity_eyebrow', 'de', $$Identität$$),
        ('app_account_page', 'identity_subtitle', 'es', $$Cuenta confirmada con identidad estable de usuario DCX.$$),
        ('app_account_page', 'identity_subtitle', 'fr', $$Compte confirmé avec une identité utilisateur DCX stable.$$),
        ('app_account_page', 'identity_subtitle', 'de', $$Bestätigtes Konto mit stabiler DCX-Benutzeridentität.$$),
        ('app_account_page', 'account_state_confirmed', 'es', $$Confirmada$$),
        ('app_account_page', 'account_state_confirmed', 'fr', $$Confirmé$$),
        ('app_account_page', 'account_state_confirmed', 'de', $$Bestätigt$$),
        ('app_account_page', 'account_state_pending', 'es', $$Pendiente$$),
        ('app_account_page', 'account_state_pending', 'fr', $$En attente$$),
        ('app_account_page', 'account_state_pending', 'de', $$Ausstehend$$),
        ('app_account_page', 'field_primary_email', 'es', $$Correo principal$$),
        ('app_account_page', 'field_primary_email', 'fr', $$E-mail principal$$),
        ('app_account_page', 'field_primary_email', 'de', $$Primäre E-Mail$$),
        ('app_account_page', 'field_primary_phone', 'es', $$Teléfono principal$$),
        ('app_account_page', 'field_primary_phone', 'fr', $$Téléphone principal$$),
        ('app_account_page', 'field_primary_phone', 'de', $$Primäre Telefonnummer$$),
        ('app_account_page', 'field_user_uuid', 'es', $$UUID de usuario$$),
        ('app_account_page', 'field_user_uuid', 'fr', $$UUID utilisateur$$),
        ('app_account_page', 'field_user_uuid', 'de', $$Benutzer-UUID$$),
        ('app_account_page', 'field_account_status', 'es', $$Estado de la cuenta$$),
        ('app_account_page', 'field_account_status', 'fr', $$Statut du compte$$),
        ('app_account_page', 'field_account_status', 'de', $$Kontostatus$$),
        ('app_account_page', 'field_preferred_language', 'es', $$Idioma preferido$$),
        ('app_account_page', 'field_preferred_language', 'fr', $$Langue préférée$$),
        ('app_account_page', 'field_preferred_language', 'de', $$Bevorzugte Sprache$$),
        ('app_account_page', 'field_timezone', 'es', $$Zona horaria$$),
        ('app_account_page', 'field_timezone', 'fr', $$Fuseau horaire$$),
        ('app_account_page', 'field_timezone', 'de', $$Zeitzone$$),
        ('app_account_page', 'field_email_preference', 'es', $$Preferencia de correo$$),
        ('app_account_page', 'field_email_preference', 'fr', $$Préférence e-mail$$),
        ('app_account_page', 'field_email_preference', 'de', $$E-Mail-Präferenz$$),
        ('app_account_page', 'field_email_confirmed_at', 'es', $$Correo confirmado el$$),
        ('app_account_page', 'field_email_confirmed_at', 'fr', $$E-mail confirmé le$$),
        ('app_account_page', 'field_email_confirmed_at', 'de', $$E-Mail bestätigt am$$),
        ('app_account_page', 'field_phone_confirmed_at', 'es', $$Teléfono confirmado el$$),
        ('app_account_page', 'field_phone_confirmed_at', 'fr', $$Téléphone confirmé le$$),
        ('app_account_page', 'field_phone_confirmed_at', 'de', $$Telefon bestätigt am$$),
        ('app_account_page', 'field_last_seen_at', 'es', $$Última actividad$$),
        ('app_account_page', 'field_last_seen_at', 'fr', $$Dernière activité$$),
        ('app_account_page', 'field_last_seen_at', 'de', $$Zuletzt aktiv$$),
        ('app_account_page', 'field_created_at', 'es', $$Creada el$$),
        ('app_account_page', 'field_created_at', 'fr', $$Créé le$$),
        ('app_account_page', 'field_created_at', 'de', $$Erstellt am$$),
        ('app_account_page', 'field_updated_at', 'es', $$Actualizada el$$),
        ('app_account_page', 'field_updated_at', 'fr', $$Mis à jour le$$),
        ('app_account_page', 'field_updated_at', 'de', $$Aktualisiert am$$),
        ('app_account_page', 'field_not_set', 'es', $$No configurado$$),
        ('app_account_page', 'field_not_set', 'fr', $$Non défini$$),
        ('app_account_page', 'field_not_set', 'de', $$Nicht festgelegt$$),
        ('app_account_page', 'field_phone_not_set_yet', 'es', $$Todavía no configurado$$),
        ('app_account_page', 'field_phone_not_set_yet', 'fr', $$Pas encore défini$$),
        ('app_account_page', 'field_phone_not_set_yet', 'de', $$Noch nicht festgelegt$$),
        ('app_account_page', 'logout_button_pending_label', 'es', $$Cerrando sesión...$$),
        ('app_account_page', 'logout_button_pending_label', 'fr', $$Déconnexion en cours...$$),
        ('app_account_page', 'logout_button_pending_label', 'de', $$Abmeldung läuft...$$),
        ('app_account_page', 'logout_button_label', 'es', $$Cerrar sesión$$),
        ('app_account_page', 'logout_button_label', 'fr', $$Se déconnecter$$),
        ('app_account_page', 'logout_button_label', 'de', $$Abmelden$$),
        ('app_account_page', 'editable_status_idle', 'es', $$El azul significa editable. Haz clic para ajustarlo.$$),
        ('app_account_page', 'editable_status_idle', 'fr', $$Le bleu signifie modifiable. Cliquez pour ajuster.$$),
        ('app_account_page', 'editable_status_idle', 'de', $$Blau bedeutet bearbeitbar. Klicken Sie zum Anpassen.$$),
        ('app_account_page', 'editable_status_editing', 'es', $$Editando. Elige un valor para autoguardar.$$),
        ('app_account_page', 'editable_status_editing', 'fr', $$Modification en cours. Choisissez une valeur pour sauvegarder automatiquement.$$),
        ('app_account_page', 'editable_status_editing', 'de', $$Bearbeitung läuft. Wählen Sie einen Wert zum automatischen Speichern.$$),
        ('app_account_page', 'editable_status_saving', 'es', $$Guardando...$$),
        ('app_account_page', 'editable_status_saving', 'fr', $$Enregistrement en cours...$$),
        ('app_account_page', 'editable_status_saving', 'de', $$Wird gespeichert...$$),
        ('app_account_page', 'editable_status_saved', 'es', $$Guardado.$$),
        ('app_account_page', 'editable_status_saved', 'fr', $$Enregistré.$$),
        ('app_account_page', 'editable_status_saved', 'de', $$Gespeichert.$$),
        ('app_account_page', 'editable_status_retrying_template', 'es', $$Reintentando guardado ({attempt}/{total})...$$),
        ('app_account_page', 'editable_status_retrying_template', 'fr', $$Nouvelle tentative d'enregistrement ({attempt}/{total})...$$),
        ('app_account_page', 'editable_status_retrying_template', 'de', $$Speichern wird erneut versucht ({attempt}/{total})...$$),
        ('app_account_page', 'editable_status_save_failed', 'es', $$El guardado falló. Haz clic de nuevo y vuelve a intentarlo.$$),
        ('app_account_page', 'editable_status_save_failed', 'fr', $$L'enregistrement a échoué. Cliquez de nouveau et réessayez.$$),
        ('app_account_page', 'editable_status_save_failed', 'de', $$Das Speichern ist fehlgeschlagen. Klicken Sie erneut hinein und versuchen Sie es noch einmal.$$),
        ('app_account_page', 'editable_status_saving_default_language', 'es', $$Guardando el idioma predeterminado...$$),
        ('app_account_page', 'editable_status_saving_default_language', 'fr', $$Enregistrement de la langue par défaut...$$),
        ('app_account_page', 'editable_status_saving_default_language', 'de', $$Standardsprache wird gespeichert...$$),
        ('app_account_page', 'error_account_load_suggested_action', 'es', $$Vuelve a iniciar sesión mediante el flujo de acceso de la app de DCX y después inténtalo de nuevo.$$),
        ('app_account_page', 'error_account_load_suggested_action', 'fr', $$Reconnectez-vous via le flux de connexion de l'application DCX, puis réessayez.$$),
        ('app_account_page', 'error_account_load_suggested_action', 'de', $$Melden Sie sich erneut über den DCX-App-Login an und versuchen Sie es dann erneut.$$),
        ('app_account_page', 'activity_eyebrow', 'es', $$Actividad$$),
        ('app_account_page', 'activity_eyebrow', 'fr', $$Activité$$),
        ('app_account_page', 'activity_eyebrow', 'de', $$Aktivität$$),
        ('app_account_page', 'activity_title', 'es', $$Cronología de la cuenta$$),
        ('app_account_page', 'activity_title', 'fr', $$Chronologie du compte$$),
        ('app_account_page', 'activity_title', 'de', $$Konto-Zeitleiste$$),
        ('app_account_page', 'email_preference_announcements', 'es', $$Anuncios$$),
        ('app_account_page', 'email_preference_announcements', 'fr', $$Annonces$$),
        ('app_account_page', 'email_preference_announcements', 'de', $$Ankündigungen$$),
        ('app_account_page', 'email_preference_essential_only', 'es', $$Solo esenciales$$),
        ('app_account_page', 'email_preference_essential_only', 'fr', $$Essentiel uniquement$$),
        ('app_account_page', 'email_preference_essential_only', 'de', $$Nur Wesentliches$$),
        ('app_account_page', 'next_eyebrow', 'es', $$Siguiente$$),
        ('app_account_page', 'next_eyebrow', 'fr', $$Suite$$),
        ('app_account_page', 'next_eyebrow', 'de', $$Als Nächstes$$),
        ('app_account_page', 'next_title', 'es', $$Los cambios de correo y teléfono pueden llegar después de demostrar el comportamiento del campo.$$),
        ('app_account_page', 'next_title', 'fr', $$Les changements d'e-mail et de téléphone peuvent venir après validation du comportement des champs.$$),
        ('app_account_page', 'next_title', 'de', $$E-Mail- und Telefonänderungen können folgen, sobald das Feldverhalten bewiesen ist.$$),
        ('app_account_page', 'next_body', 'es', $$Esta fase mantiene el correo principal y el teléfono como solo lectura de forma intencionada. El idioma preferido, la zona horaria y la preferencia de comunicación prueban ahora el autoguardado en línea, la ruta de reintento y la respuesta visual de guardado que luego podremos reutilizar para cambios de cuenta de mayor riesgo.$$),
        ('app_account_page', 'next_body', 'fr', $$Cette étape garde volontairement l'e-mail principal et le téléphone en lecture seule. La langue préférée, le fuseau horaire et la préférence de communication valident maintenant le comportement d'enregistrement en ligne, le chemin de nouvelle tentative et le retour visuel d'enregistrement que nous pourrons réutiliser plus tard pour des changements de compte plus risqués.$$),
        ('app_account_page', 'next_body', 'de', $$In diesem Schritt bleiben primäre E-Mail und Telefon bewusst schreibgeschützt. Bevorzugte Sprache, Zeitzone und Kommunikationspräferenz beweisen jetzt das Inline-Autospeichern, den Wiederholungsweg und das Save-Feedback, das wir später für risikoreichere Kontoänderungen wiederverwenden können.$$)
),
language_rows AS (
    SELECT id, language_code
    FROM stephen_dcx_languages
    WHERE language_code IN ('en', 'es', 'fr', 'de')
),
english_live_originals AS (
    SELECT
        originals.id,
        originals.string_group,
        originals.string_key
    FROM stephen_dcx_ux_strings originals
    JOIN language_rows english_language
      ON english_language.id = originals.language_id
     AND english_language.language_code = 'en'
    WHERE originals.is_original = TRUE
      AND originals.is_live = TRUE
)
INSERT INTO stephen_dcx_ux_strings
(string_group, string_key, language_id, text, is_original, is_live, version_of_id, translation_of_id)
SELECT
    desired_translations.string_group,
    desired_translations.string_key,
    target_language.id,
    desired_translations.text_value,
    FALSE,
    TRUE,
    NULL,
    english_live_originals.id
FROM desired_translations
JOIN language_rows target_language
  ON target_language.language_code = desired_translations.language_code
JOIN english_live_originals
  ON english_live_originals.string_group = desired_translations.string_group
 AND english_live_originals.string_key = desired_translations.string_key
WHERE NOT EXISTS (
    SELECT 1
    FROM stephen_dcx_ux_strings existing
    WHERE existing.string_group = desired_translations.string_group
      AND existing.string_key = desired_translations.string_key
      AND existing.language_id = target_language.id
      AND existing.is_live = TRUE
);
