-- CONTEXT:
-- Seeds the summer marketing reference data needed before the old-DCX outreach pass.
-- It expands the basic selectable/reference lists only: target languages, countries with
-- primary calling codes, and trade-interest material options.
--
-- CONTRACT:
-- - Safe to rerun locally and live.
-- - Does not delete existing rows.
-- - Does not import old users, contacts, companies, or CRM records.
-- - Does not seed UX strings, newsletters, grouped dropdown UI, or material parsing rules.

BEGIN;

WITH desired_languages(
    language_code,
    language_name_en,
    language_name_native,
    is_rtl,
    is_default
) AS (
    VALUES
        ('en', 'English', 'English', FALSE, TRUE),
        ('zh', 'Chinese', U&'\4E2D\6587', FALSE, FALSE),
        ('hi', 'Hindi', U&'\0939\093F\0928\094D\0926\0940', FALSE, FALSE),
        ('ur', 'Urdu', U&'\0627\0631\062F\0648', TRUE, FALSE),
        ('vi', 'Vietnamese', U&'Ti\1EBFng Vi\1EC7t', FALSE, FALSE),
        ('id', 'Indonesian', 'Bahasa Indonesia', FALSE, FALSE),
        ('ar', 'Arabic', U&'\0627\0644\0639\0631\0628\064A\0629', TRUE, FALSE),
        ('tr', 'Turkish', U&'T\00FCrk\00E7e', FALSE, FALSE),
        ('ru', 'Russian', U&'\0420\0443\0441\0441\043A\0438\0439', FALSE, FALSE),
        ('pt', 'Portuguese', U&'Portugu\00EAs', FALSE, FALSE),
        ('es', 'Spanish', U&'Espa\00F1ol', FALSE, FALSE),
        ('fr', 'French', U&'Fran\00E7ais', FALSE, FALSE),
        ('de', 'German', 'Deutsch', FALSE, FALSE)
)
INSERT INTO stephen_dcx_languages (
    language_code,
    language_name_en,
    language_name_native,
    is_rtl,
    is_active,
    is_default
)
SELECT
    desired_languages.language_code,
    desired_languages.language_name_en,
    desired_languages.language_name_native,
    desired_languages.is_rtl,
    TRUE,
    desired_languages.is_default
FROM desired_languages
ON CONFLICT (language_code) DO UPDATE
SET
    language_name_en = EXCLUDED.language_name_en,
    language_name_native = EXCLUDED.language_name_native,
    is_rtl = EXCLUDED.is_rtl,
    is_active = TRUE,
    is_default = EXCLUDED.is_default,
    updated_at_ts_ms = ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint);

WITH country_seed(country_code_alpha2, default_display_name, flag_asset_key, sort_order) AS (
    VALUES
        ('AF', 'Afghanistan', 'af', 1000),
        ('AX', 'Aland Islands', 'ax', 1000),
        ('AL', 'Albania', 'al', 1000),
        ('DZ', 'Algeria', 'dz', 1000),
        ('AS', 'American Samoa', 'as', 1000),
        ('AD', 'Andorra', 'ad', 1000),
        ('AO', 'Angola', 'ao', 1000),
        ('AI', 'Anguilla', 'ai', 1000),
        ('AQ', 'Antarctica', 'aq', 1000),
        ('AG', 'Antigua and Barbuda', 'ag', 1000),
        ('AR', 'Argentina', 'ar', 1000),
        ('AM', 'Armenia', 'am', 1000),
        ('AW', 'Aruba', 'aw', 1000),
        ('AU', 'Australia', 'au', 1000),
        ('AT', 'Austria', 'at', 1000),
        ('AZ', 'Azerbaijan', 'az', 1000),
        ('BS', 'Bahamas', 'bs', 1000),
        ('BH', 'Bahrain', 'bh', 1000),
        ('BD', 'Bangladesh', 'bd', 1000),
        ('BB', 'Barbados', 'bb', 1000),
        ('BY', 'Belarus', 'by', 1000),
        ('BE', 'Belgium', 'be', 1000),
        ('BZ', 'Belize', 'bz', 1000),
        ('BJ', 'Benin', 'bj', 1000),
        ('BM', 'Bermuda', 'bm', 1000),
        ('BT', 'Bhutan', 'bt', 1000),
        ('BO', 'Bolivia', 'bo', 1000),
        ('BQ', 'Bonaire, Sint Eustatius and Saba', 'bq', 1000),
        ('BA', 'Bosnia and Herzegovina', 'ba', 1000),
        ('BW', 'Botswana', 'bw', 1000),
        ('BV', 'Bouvet Island', 'bv', 1000),
        ('BR', 'Brazil', 'br', 1000),
        ('IO', 'British Indian Ocean Territory', 'io', 1000),
        ('BN', 'Brunei', 'bn', 1000),
        ('BG', 'Bulgaria', 'bg', 1000),
        ('BF', 'Burkina Faso', 'bf', 1000),
        ('BI', 'Burundi', 'bi', 1000),
        ('CV', 'Cabo Verde', 'cv', 1000),
        ('KH', 'Cambodia', 'kh', 1000),
        ('CM', 'Cameroon', 'cm', 1000),
        ('CA', 'Canada', 'ca', 1000),
        ('KY', 'Cayman Islands', 'ky', 1000),
        ('CF', 'Central African Republic', 'cf', 1000),
        ('TD', 'Chad', 'td', 1000),
        ('CL', 'Chile', 'cl', 1000),
        ('CN', 'China', 'cn', 1000),
        ('CX', 'Christmas Island', 'cx', 1000),
        ('CC', 'Cocos (Keeling) Islands', 'cc', 1000),
        ('CO', 'Colombia', 'co', 1000),
        ('KM', 'Comoros', 'km', 1000),
        ('CG', 'Congo', 'cg', 1000),
        ('CD', 'Congo, Democratic Republic of the', 'cd', 1000),
        ('CK', 'Cook Islands', 'ck', 1000),
        ('CR', 'Costa Rica', 'cr', 1000),
        ('CI', 'Cote d''Ivoire', 'ci', 1000),
        ('HR', 'Croatia', 'hr', 1000),
        ('CU', 'Cuba', 'cu', 1000),
        ('CW', 'Curacao', 'cw', 1000),
        ('CY', 'Cyprus', 'cy', 1000),
        ('CZ', 'Czechia', 'cz', 1000),
        ('DK', 'Denmark', 'dk', 1000),
        ('DJ', 'Djibouti', 'dj', 1000),
        ('DM', 'Dominica', 'dm', 1000),
        ('DO', 'Dominican Republic', 'do', 1000),
        ('EC', 'Ecuador', 'ec', 1000),
        ('EG', 'Egypt', 'eg', 1000),
        ('SV', 'El Salvador', 'sv', 1000),
        ('GQ', 'Equatorial Guinea', 'gq', 1000),
        ('ER', 'Eritrea', 'er', 1000),
        ('EE', 'Estonia', 'ee', 1000),
        ('SZ', 'Eswatini', 'sz', 1000),
        ('ET', 'Ethiopia', 'et', 1000),
        ('FK', 'Falkland Islands', 'fk', 1000),
        ('FO', 'Faroe Islands', 'fo', 1000),
        ('FJ', 'Fiji', 'fj', 1000),
        ('FI', 'Finland', 'fi', 1000),
        ('FR', 'France', 'fr', 1000),
        ('GF', 'French Guiana', 'gf', 1000),
        ('PF', 'French Polynesia', 'pf', 1000),
        ('TF', 'French Southern Territories', 'tf', 1000),
        ('GA', 'Gabon', 'ga', 1000),
        ('GM', 'Gambia', 'gm', 1000),
        ('GE', 'Georgia', 'ge', 1000),
        ('DE', 'Germany', 'de', 1000),
        ('GH', 'Ghana', 'gh', 1000),
        ('GI', 'Gibraltar', 'gi', 1000),
        ('GR', 'Greece', 'gr', 1000),
        ('GL', 'Greenland', 'gl', 1000),
        ('GD', 'Grenada', 'gd', 1000),
        ('GP', 'Guadeloupe', 'gp', 1000),
        ('GU', 'Guam', 'gu', 1000),
        ('GT', 'Guatemala', 'gt', 1000),
        ('GG', 'Guernsey', 'gg', 1000),
        ('GN', 'Guinea', 'gn', 1000),
        ('GW', 'Guinea-Bissau', 'gw', 1000),
        ('GY', 'Guyana', 'gy', 1000),
        ('HT', 'Haiti', 'ht', 1000),
        ('HM', 'Heard Island and McDonald Islands', 'hm', 1000),
        ('VA', 'Holy See', 'va', 1000),
        ('HN', 'Honduras', 'hn', 1000),
        ('HK', 'Hong Kong', 'hk', 1000),
        ('HU', 'Hungary', 'hu', 1000),
        ('IS', 'Iceland', 'is', 1000),
        ('IN', 'India', 'in', 1000),
        ('ID', 'Indonesia', 'id', 1000),
        ('IR', 'Iran', 'ir', 1000),
        ('IQ', 'Iraq', 'iq', 1000),
        ('IE', 'Ireland', 'ie', 1000),
        ('IM', 'Isle of Man', 'im', 1000),
        ('IL', 'Israel', 'il', 1000),
        ('IT', 'Italy', 'it', 1000),
        ('JM', 'Jamaica', 'jm', 1000),
        ('JP', 'Japan', 'jp', 1000),
        ('JE', 'Jersey', 'je', 1000),
        ('JO', 'Jordan', 'jo', 1000),
        ('KZ', 'Kazakhstan', 'kz', 1000),
        ('KE', 'Kenya', 'ke', 1000),
        ('KI', 'Kiribati', 'ki', 1000),
        ('XK', 'Kosovo', 'xk', 1000),
        ('KW', 'Kuwait', 'kw', 1000),
        ('KG', 'Kyrgyzstan', 'kg', 1000),
        ('LA', 'Laos', 'la', 1000),
        ('LV', 'Latvia', 'lv', 1000),
        ('LB', 'Lebanon', 'lb', 1000),
        ('LS', 'Lesotho', 'ls', 1000),
        ('LR', 'Liberia', 'lr', 1000),
        ('LY', 'Libya', 'ly', 1000),
        ('LI', 'Liechtenstein', 'li', 1000),
        ('LT', 'Lithuania', 'lt', 1000),
        ('LU', 'Luxembourg', 'lu', 1000),
        ('MO', 'Macao', 'mo', 1000),
        ('MG', 'Madagascar', 'mg', 1000),
        ('MW', 'Malawi', 'mw', 1000),
        ('MY', 'Malaysia', 'my', 1000),
        ('MV', 'Maldives', 'mv', 1000),
        ('ML', 'Mali', 'ml', 1000),
        ('MT', 'Malta', 'mt', 1000),
        ('MH', 'Marshall Islands', 'mh', 1000),
        ('MQ', 'Martinique', 'mq', 1000),
        ('MR', 'Mauritania', 'mr', 1000),
        ('MU', 'Mauritius', 'mu', 1000),
        ('YT', 'Mayotte', 'yt', 1000),
        ('MX', 'Mexico', 'mx', 1000),
        ('FM', 'Micronesia', 'fm', 1000),
        ('MD', 'Moldova', 'md', 1000),
        ('MC', 'Monaco', 'mc', 1000),
        ('MN', 'Mongolia', 'mn', 1000),
        ('ME', 'Montenegro', 'me', 1000),
        ('MS', 'Montserrat', 'ms', 1000),
        ('MA', 'Morocco', 'ma', 1000),
        ('MZ', 'Mozambique', 'mz', 1000),
        ('MM', 'Myanmar', 'mm', 1000),
        ('NA', 'Namibia', 'na', 1000),
        ('NR', 'Nauru', 'nr', 1000),
        ('NP', 'Nepal', 'np', 1000),
        ('NL', 'Netherlands', 'nl', 1000),
        ('NC', 'New Caledonia', 'nc', 1000),
        ('NZ', 'New Zealand', 'nz', 1000),
        ('NI', 'Nicaragua', 'ni', 1000),
        ('NE', 'Niger', 'ne', 1000),
        ('NG', 'Nigeria', 'ng', 1000),
        ('NU', 'Niue', 'nu', 1000),
        ('NF', 'Norfolk Island', 'nf', 1000),
        ('KP', 'North Korea', 'kp', 1000),
        ('MK', 'North Macedonia', 'mk', 1000),
        ('MP', 'Northern Mariana Islands', 'mp', 1000),
        ('NO', 'Norway', 'no', 1000),
        ('OM', 'Oman', 'om', 1000),
        ('PK', 'Pakistan', 'pk', 1000),
        ('PW', 'Palau', 'pw', 1000),
        ('PS', 'Palestine', 'ps', 1000),
        ('PA', 'Panama', 'pa', 1000),
        ('PG', 'Papua New Guinea', 'pg', 1000),
        ('PY', 'Paraguay', 'py', 1000),
        ('PE', 'Peru', 'pe', 1000),
        ('PH', 'Philippines', 'ph', 1000),
        ('PN', 'Pitcairn', 'pn', 1000),
        ('PL', 'Poland', 'pl', 1000),
        ('PT', 'Portugal', 'pt', 1000),
        ('PR', 'Puerto Rico', 'pr', 1000),
        ('QA', 'Qatar', 'qa', 1000),
        ('RE', 'Reunion', 're', 1000),
        ('RO', 'Romania', 'ro', 1000),
        ('RU', 'Russia', 'ru', 1000),
        ('RW', 'Rwanda', 'rw', 1000),
        ('BL', 'Saint Barthelemy', 'bl', 1000),
        ('SH', 'Saint Helena', 'sh', 1000),
        ('KN', 'Saint Kitts and Nevis', 'kn', 1000),
        ('LC', 'Saint Lucia', 'lc', 1000),
        ('MF', 'Saint Martin', 'mf', 1000),
        ('PM', 'Saint Pierre and Miquelon', 'pm', 1000),
        ('VC', 'Saint Vincent and the Grenadines', 'vc', 1000),
        ('WS', 'Samoa', 'ws', 1000),
        ('SM', 'San Marino', 'sm', 1000),
        ('ST', 'Sao Tome and Principe', 'st', 1000),
        ('SA', 'Saudi Arabia', 'sa', 1000),
        ('SN', 'Senegal', 'sn', 1000),
        ('RS', 'Serbia', 'rs', 1000),
        ('SC', 'Seychelles', 'sc', 1000),
        ('SL', 'Sierra Leone', 'sl', 1000),
        ('SG', 'Singapore', 'sg', 1000),
        ('SX', 'Sint Maarten', 'sx', 1000),
        ('SK', 'Slovakia', 'sk', 1000),
        ('SI', 'Slovenia', 'si', 1000),
        ('SB', 'Solomon Islands', 'sb', 1000),
        ('SO', 'Somalia', 'so', 1000),
        ('ZA', 'South Africa', 'za', 1000),
        ('GS', 'South Georgia and the South Sandwich Islands', 'gs', 1000),
        ('KR', 'South Korea', 'kr', 1000),
        ('SS', 'South Sudan', 'ss', 1000),
        ('ES', 'Spain', 'es', 1000),
        ('LK', 'Sri Lanka', 'lk', 1000),
        ('SD', 'Sudan', 'sd', 1000),
        ('SR', 'Suriname', 'sr', 1000),
        ('SJ', 'Svalbard and Jan Mayen', 'sj', 1000),
        ('SE', 'Sweden', 'se', 1000),
        ('CH', 'Switzerland', 'ch', 1000),
        ('SY', 'Syria', 'sy', 1000),
        ('TW', 'Taiwan', 'tw', 1000),
        ('TJ', 'Tajikistan', 'tj', 1000),
        ('TZ', 'Tanzania', 'tz', 1000),
        ('TH', 'Thailand', 'th', 1000),
        ('TL', 'Timor-Leste', 'tl', 1000),
        ('TG', 'Togo', 'tg', 1000),
        ('TK', 'Tokelau', 'tk', 1000),
        ('TO', 'Tonga', 'to', 1000),
        ('TT', 'Trinidad and Tobago', 'tt', 1000),
        ('TN', 'Tunisia', 'tn', 1000),
        ('TR', 'Turkey', 'tr', 1000),
        ('TM', 'Turkmenistan', 'tm', 1000),
        ('TC', 'Turks and Caicos Islands', 'tc', 1000),
        ('TV', 'Tuvalu', 'tv', 1000),
        ('UG', 'Uganda', 'ug', 1000),
        ('UA', 'Ukraine', 'ua', 1000),
        ('AE', 'United Arab Emirates', 'ae', 1000),
        ('GB', 'United Kingdom', 'gb', 1000),
        ('UM', 'United States Minor Outlying Islands', 'um', 1000),
        ('US', 'United States', 'us', 1000),
        ('UY', 'Uruguay', 'uy', 1000),
        ('UZ', 'Uzbekistan', 'uz', 1000),
        ('VU', 'Vanuatu', 'vu', 1000),
        ('VE', 'Venezuela', 've', 1000),
        ('VN', 'Vietnam', 'vn', 1000),
        ('VG', 'Virgin Islands, British', 'vg', 1000),
        ('VI', 'Virgin Islands, U.S.', 'vi', 1000),
        ('WF', 'Wallis and Futuna', 'wf', 1000),
        ('EH', 'Western Sahara', 'eh', 1000),
        ('YE', 'Yemen', 'ye', 1000),
        ('ZM', 'Zambia', 'zm', 1000),
        ('ZW', 'Zimbabwe', 'zw', 1000)
)
INSERT INTO stephen_dcx_countries (
    country_code_alpha2,
    default_display_name,
    flag_asset_key,
    sort_order
)
SELECT
    country_seed.country_code_alpha2,
    country_seed.default_display_name,
    country_seed.flag_asset_key,
    country_seed.sort_order
FROM country_seed
ON CONFLICT (country_code_alpha2) DO UPDATE
SET
    default_display_name = EXCLUDED.default_display_name,
    flag_asset_key = EXCLUDED.flag_asset_key,
    sort_order = EXCLUDED.sort_order,
    is_active = TRUE,
    updated_at_ts_ms = ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint);

WITH calling_code_seed(country_code_alpha2, calling_code, is_primary, sort_order) AS (
    VALUES
        ('AF', '+93', TRUE, 10),
        ('AX', '+358', TRUE, 10),
        ('AL', '+355', TRUE, 10),
        ('DZ', '+213', TRUE, 10),
        ('AS', '+1', TRUE, 10),
        ('AD', '+376', TRUE, 10),
        ('AO', '+244', TRUE, 10),
        ('AI', '+1', TRUE, 10),
        ('AQ', '+672', TRUE, 10),
        ('AG', '+1', TRUE, 10),
        ('AR', '+54', TRUE, 10),
        ('AM', '+374', TRUE, 10),
        ('AW', '+297', TRUE, 10),
        ('AU', '+61', TRUE, 10),
        ('AT', '+43', TRUE, 10),
        ('AZ', '+994', TRUE, 10),
        ('BS', '+1', TRUE, 10),
        ('BH', '+973', TRUE, 10),
        ('BD', '+880', TRUE, 10),
        ('BB', '+1', TRUE, 10),
        ('BY', '+375', TRUE, 10),
        ('BE', '+32', TRUE, 10),
        ('BZ', '+501', TRUE, 10),
        ('BJ', '+229', TRUE, 10),
        ('BM', '+1', TRUE, 10),
        ('BT', '+975', TRUE, 10),
        ('BO', '+591', TRUE, 10),
        ('BQ', '+599', TRUE, 10),
        ('BA', '+387', TRUE, 10),
        ('BW', '+267', TRUE, 10),
        ('BV', '+47', TRUE, 10),
        ('BR', '+55', TRUE, 10),
        ('IO', '+246', TRUE, 10),
        ('BN', '+673', TRUE, 10),
        ('BG', '+359', TRUE, 10),
        ('BF', '+226', TRUE, 10),
        ('BI', '+257', TRUE, 10),
        ('CV', '+238', TRUE, 10),
        ('KH', '+855', TRUE, 10),
        ('CM', '+237', TRUE, 10),
        ('CA', '+1', TRUE, 10),
        ('KY', '+1', TRUE, 10),
        ('CF', '+236', TRUE, 10),
        ('TD', '+235', TRUE, 10),
        ('CL', '+56', TRUE, 10),
        ('CN', '+86', TRUE, 10),
        ('CX', '+61', TRUE, 10),
        ('CC', '+61', TRUE, 10),
        ('CO', '+57', TRUE, 10),
        ('KM', '+269', TRUE, 10),
        ('CG', '+242', TRUE, 10),
        ('CD', '+243', TRUE, 10),
        ('CK', '+682', TRUE, 10),
        ('CR', '+506', TRUE, 10),
        ('CI', '+225', TRUE, 10),
        ('HR', '+385', TRUE, 10),
        ('CU', '+53', TRUE, 10),
        ('CW', '+599', TRUE, 10),
        ('CY', '+357', TRUE, 10),
        ('CZ', '+420', TRUE, 10),
        ('DK', '+45', TRUE, 10),
        ('DJ', '+253', TRUE, 10),
        ('DM', '+1', TRUE, 10),
        ('DO', '+1', TRUE, 10),
        ('EC', '+593', TRUE, 10),
        ('EG', '+20', TRUE, 10),
        ('SV', '+503', TRUE, 10),
        ('GQ', '+240', TRUE, 10),
        ('ER', '+291', TRUE, 10),
        ('EE', '+372', TRUE, 10),
        ('SZ', '+268', TRUE, 10),
        ('ET', '+251', TRUE, 10),
        ('FK', '+500', TRUE, 10),
        ('FO', '+298', TRUE, 10),
        ('FJ', '+679', TRUE, 10),
        ('FI', '+358', TRUE, 10),
        ('FR', '+33', TRUE, 10),
        ('GF', '+594', TRUE, 10),
        ('PF', '+689', TRUE, 10),
        ('TF', '+262', TRUE, 10),
        ('GA', '+241', TRUE, 10),
        ('GM', '+220', TRUE, 10),
        ('GE', '+995', TRUE, 10),
        ('DE', '+49', TRUE, 10),
        ('GH', '+233', TRUE, 10),
        ('GI', '+350', TRUE, 10),
        ('GR', '+30', TRUE, 10),
        ('GL', '+299', TRUE, 10),
        ('GD', '+1', TRUE, 10),
        ('GP', '+590', TRUE, 10),
        ('GU', '+1', TRUE, 10),
        ('GT', '+502', TRUE, 10),
        ('GG', '+44', TRUE, 10),
        ('GN', '+224', TRUE, 10),
        ('GW', '+245', TRUE, 10),
        ('GY', '+592', TRUE, 10),
        ('HT', '+509', TRUE, 10),
        ('HM', '+672', TRUE, 10),
        ('VA', '+39', TRUE, 10),
        ('HN', '+504', TRUE, 10),
        ('HK', '+852', TRUE, 10),
        ('HU', '+36', TRUE, 10),
        ('IS', '+354', TRUE, 10),
        ('IN', '+91', TRUE, 10),
        ('ID', '+62', TRUE, 10),
        ('IR', '+98', TRUE, 10),
        ('IQ', '+964', TRUE, 10),
        ('IE', '+353', TRUE, 10),
        ('IM', '+44', TRUE, 10),
        ('IL', '+972', TRUE, 10),
        ('IT', '+39', TRUE, 10),
        ('JM', '+1', TRUE, 10),
        ('JP', '+81', TRUE, 10),
        ('JE', '+44', TRUE, 10),
        ('JO', '+962', TRUE, 10),
        ('KZ', '+7', TRUE, 10),
        ('KE', '+254', TRUE, 10),
        ('KI', '+686', TRUE, 10),
        ('XK', '+383', TRUE, 10),
        ('KW', '+965', TRUE, 10),
        ('KG', '+996', TRUE, 10),
        ('LA', '+856', TRUE, 10),
        ('LV', '+371', TRUE, 10),
        ('LB', '+961', TRUE, 10),
        ('LS', '+266', TRUE, 10),
        ('LR', '+231', TRUE, 10),
        ('LY', '+218', TRUE, 10),
        ('LI', '+423', TRUE, 10),
        ('LT', '+370', TRUE, 10),
        ('LU', '+352', TRUE, 10),
        ('MO', '+853', TRUE, 10),
        ('MG', '+261', TRUE, 10),
        ('MW', '+265', TRUE, 10),
        ('MY', '+60', TRUE, 10),
        ('MV', '+960', TRUE, 10),
        ('ML', '+223', TRUE, 10),
        ('MT', '+356', TRUE, 10),
        ('MH', '+692', TRUE, 10),
        ('MQ', '+596', TRUE, 10),
        ('MR', '+222', TRUE, 10),
        ('MU', '+230', TRUE, 10),
        ('YT', '+262', TRUE, 10),
        ('MX', '+52', TRUE, 10),
        ('FM', '+691', TRUE, 10),
        ('MD', '+373', TRUE, 10),
        ('MC', '+377', TRUE, 10),
        ('MN', '+976', TRUE, 10),
        ('ME', '+382', TRUE, 10),
        ('MS', '+1', TRUE, 10),
        ('MA', '+212', TRUE, 10),
        ('MZ', '+258', TRUE, 10),
        ('MM', '+95', TRUE, 10),
        ('NA', '+264', TRUE, 10),
        ('NR', '+674', TRUE, 10),
        ('NP', '+977', TRUE, 10),
        ('NL', '+31', TRUE, 10),
        ('NC', '+687', TRUE, 10),
        ('NZ', '+64', TRUE, 10),
        ('NI', '+505', TRUE, 10),
        ('NE', '+227', TRUE, 10),
        ('NG', '+234', TRUE, 10),
        ('NU', '+683', TRUE, 10),
        ('NF', '+672', TRUE, 10),
        ('KP', '+850', TRUE, 10),
        ('MK', '+389', TRUE, 10),
        ('MP', '+1', TRUE, 10),
        ('NO', '+47', TRUE, 10),
        ('OM', '+968', TRUE, 10),
        ('PK', '+92', TRUE, 10),
        ('PW', '+680', TRUE, 10),
        ('PS', '+970', TRUE, 10),
        ('PA', '+507', TRUE, 10),
        ('PG', '+675', TRUE, 10),
        ('PY', '+595', TRUE, 10),
        ('PE', '+51', TRUE, 10),
        ('PH', '+63', TRUE, 10),
        ('PN', '+64', TRUE, 10),
        ('PL', '+48', TRUE, 10),
        ('PT', '+351', TRUE, 10),
        ('PR', '+1', TRUE, 10),
        ('QA', '+974', TRUE, 10),
        ('RE', '+262', TRUE, 10),
        ('RO', '+40', TRUE, 10),
        ('RU', '+7', TRUE, 10),
        ('RW', '+250', TRUE, 10),
        ('BL', '+590', TRUE, 10),
        ('SH', '+290', TRUE, 10),
        ('KN', '+1', TRUE, 10),
        ('LC', '+1', TRUE, 10),
        ('MF', '+590', TRUE, 10),
        ('PM', '+508', TRUE, 10),
        ('VC', '+1', TRUE, 10),
        ('WS', '+685', TRUE, 10),
        ('SM', '+378', TRUE, 10),
        ('ST', '+239', TRUE, 10),
        ('SA', '+966', TRUE, 10),
        ('SN', '+221', TRUE, 10),
        ('RS', '+381', TRUE, 10),
        ('SC', '+248', TRUE, 10),
        ('SL', '+232', TRUE, 10),
        ('SG', '+65', TRUE, 10),
        ('SX', '+1', TRUE, 10),
        ('SK', '+421', TRUE, 10),
        ('SI', '+386', TRUE, 10),
        ('SB', '+677', TRUE, 10),
        ('SO', '+252', TRUE, 10),
        ('ZA', '+27', TRUE, 10),
        ('GS', '+500', TRUE, 10),
        ('KR', '+82', TRUE, 10),
        ('SS', '+211', TRUE, 10),
        ('ES', '+34', TRUE, 10),
        ('LK', '+94', TRUE, 10),
        ('SD', '+249', TRUE, 10),
        ('SR', '+597', TRUE, 10),
        ('SJ', '+47', TRUE, 10),
        ('SE', '+46', TRUE, 10),
        ('CH', '+41', TRUE, 10),
        ('SY', '+963', TRUE, 10),
        ('TW', '+886', TRUE, 10),
        ('TJ', '+992', TRUE, 10),
        ('TZ', '+255', TRUE, 10),
        ('TH', '+66', TRUE, 10),
        ('TL', '+670', TRUE, 10),
        ('TG', '+228', TRUE, 10),
        ('TK', '+690', TRUE, 10),
        ('TO', '+676', TRUE, 10),
        ('TT', '+1', TRUE, 10),
        ('TN', '+216', TRUE, 10),
        ('TR', '+90', TRUE, 10),
        ('TM', '+993', TRUE, 10),
        ('TC', '+1', TRUE, 10),
        ('TV', '+688', TRUE, 10),
        ('UG', '+256', TRUE, 10),
        ('UA', '+380', TRUE, 10),
        ('AE', '+971', TRUE, 10),
        ('GB', '+44', TRUE, 10),
        ('UM', '+1', TRUE, 10),
        ('US', '+1', TRUE, 10),
        ('UY', '+598', TRUE, 10),
        ('UZ', '+998', TRUE, 10),
        ('VU', '+678', TRUE, 10),
        ('VE', '+58', TRUE, 10),
        ('VN', '+84', TRUE, 10),
        ('VG', '+1', TRUE, 10),
        ('VI', '+1', TRUE, 10),
        ('WF', '+681', TRUE, 10),
        ('EH', '+212', TRUE, 10),
        ('YE', '+967', TRUE, 10),
        ('ZM', '+260', TRUE, 10),
        ('ZW', '+263', TRUE, 10)
),
seeded_country_ids AS (
    SELECT country.id AS country_id, calling_code_seed.country_code_alpha2, calling_code_seed.calling_code
    FROM calling_code_seed
    JOIN stephen_dcx_countries AS country
      ON country.country_code_alpha2 = calling_code_seed.country_code_alpha2
)
UPDATE stephen_dcx_country_calling_codes AS existing_code
SET
    is_primary = FALSE,
    updated_at_ts_ms = ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint)
FROM stephen_dcx_countries AS country
WHERE existing_code.country_id = country.id
  AND country.country_code_alpha2 IN (SELECT country_code_alpha2 FROM calling_code_seed)
  AND NOT EXISTS (
      SELECT 1
      FROM seeded_country_ids
      WHERE seeded_country_ids.country_id = existing_code.country_id
        AND seeded_country_ids.calling_code = existing_code.calling_code
  );

WITH calling_code_seed(country_code_alpha2, calling_code, is_primary, sort_order) AS (
    VALUES
        ('AF', '+93', TRUE, 10),
        ('AX', '+358', TRUE, 10),
        ('AL', '+355', TRUE, 10),
        ('DZ', '+213', TRUE, 10),
        ('AS', '+1', TRUE, 10),
        ('AD', '+376', TRUE, 10),
        ('AO', '+244', TRUE, 10),
        ('AI', '+1', TRUE, 10),
        ('AQ', '+672', TRUE, 10),
        ('AG', '+1', TRUE, 10),
        ('AR', '+54', TRUE, 10),
        ('AM', '+374', TRUE, 10),
        ('AW', '+297', TRUE, 10),
        ('AU', '+61', TRUE, 10),
        ('AT', '+43', TRUE, 10),
        ('AZ', '+994', TRUE, 10),
        ('BS', '+1', TRUE, 10),
        ('BH', '+973', TRUE, 10),
        ('BD', '+880', TRUE, 10),
        ('BB', '+1', TRUE, 10),
        ('BY', '+375', TRUE, 10),
        ('BE', '+32', TRUE, 10),
        ('BZ', '+501', TRUE, 10),
        ('BJ', '+229', TRUE, 10),
        ('BM', '+1', TRUE, 10),
        ('BT', '+975', TRUE, 10),
        ('BO', '+591', TRUE, 10),
        ('BQ', '+599', TRUE, 10),
        ('BA', '+387', TRUE, 10),
        ('BW', '+267', TRUE, 10),
        ('BV', '+47', TRUE, 10),
        ('BR', '+55', TRUE, 10),
        ('IO', '+246', TRUE, 10),
        ('BN', '+673', TRUE, 10),
        ('BG', '+359', TRUE, 10),
        ('BF', '+226', TRUE, 10),
        ('BI', '+257', TRUE, 10),
        ('CV', '+238', TRUE, 10),
        ('KH', '+855', TRUE, 10),
        ('CM', '+237', TRUE, 10),
        ('CA', '+1', TRUE, 10),
        ('KY', '+1', TRUE, 10),
        ('CF', '+236', TRUE, 10),
        ('TD', '+235', TRUE, 10),
        ('CL', '+56', TRUE, 10),
        ('CN', '+86', TRUE, 10),
        ('CX', '+61', TRUE, 10),
        ('CC', '+61', TRUE, 10),
        ('CO', '+57', TRUE, 10),
        ('KM', '+269', TRUE, 10),
        ('CG', '+242', TRUE, 10),
        ('CD', '+243', TRUE, 10),
        ('CK', '+682', TRUE, 10),
        ('CR', '+506', TRUE, 10),
        ('CI', '+225', TRUE, 10),
        ('HR', '+385', TRUE, 10),
        ('CU', '+53', TRUE, 10),
        ('CW', '+599', TRUE, 10),
        ('CY', '+357', TRUE, 10),
        ('CZ', '+420', TRUE, 10),
        ('DK', '+45', TRUE, 10),
        ('DJ', '+253', TRUE, 10),
        ('DM', '+1', TRUE, 10),
        ('DO', '+1', TRUE, 10),
        ('EC', '+593', TRUE, 10),
        ('EG', '+20', TRUE, 10),
        ('SV', '+503', TRUE, 10),
        ('GQ', '+240', TRUE, 10),
        ('ER', '+291', TRUE, 10),
        ('EE', '+372', TRUE, 10),
        ('SZ', '+268', TRUE, 10),
        ('ET', '+251', TRUE, 10),
        ('FK', '+500', TRUE, 10),
        ('FO', '+298', TRUE, 10),
        ('FJ', '+679', TRUE, 10),
        ('FI', '+358', TRUE, 10),
        ('FR', '+33', TRUE, 10),
        ('GF', '+594', TRUE, 10),
        ('PF', '+689', TRUE, 10),
        ('TF', '+262', TRUE, 10),
        ('GA', '+241', TRUE, 10),
        ('GM', '+220', TRUE, 10),
        ('GE', '+995', TRUE, 10),
        ('DE', '+49', TRUE, 10),
        ('GH', '+233', TRUE, 10),
        ('GI', '+350', TRUE, 10),
        ('GR', '+30', TRUE, 10),
        ('GL', '+299', TRUE, 10),
        ('GD', '+1', TRUE, 10),
        ('GP', '+590', TRUE, 10),
        ('GU', '+1', TRUE, 10),
        ('GT', '+502', TRUE, 10),
        ('GG', '+44', TRUE, 10),
        ('GN', '+224', TRUE, 10),
        ('GW', '+245', TRUE, 10),
        ('GY', '+592', TRUE, 10),
        ('HT', '+509', TRUE, 10),
        ('HM', '+672', TRUE, 10),
        ('VA', '+39', TRUE, 10),
        ('HN', '+504', TRUE, 10),
        ('HK', '+852', TRUE, 10),
        ('HU', '+36', TRUE, 10),
        ('IS', '+354', TRUE, 10),
        ('IN', '+91', TRUE, 10),
        ('ID', '+62', TRUE, 10),
        ('IR', '+98', TRUE, 10),
        ('IQ', '+964', TRUE, 10),
        ('IE', '+353', TRUE, 10),
        ('IM', '+44', TRUE, 10),
        ('IL', '+972', TRUE, 10),
        ('IT', '+39', TRUE, 10),
        ('JM', '+1', TRUE, 10),
        ('JP', '+81', TRUE, 10),
        ('JE', '+44', TRUE, 10),
        ('JO', '+962', TRUE, 10),
        ('KZ', '+7', TRUE, 10),
        ('KE', '+254', TRUE, 10),
        ('KI', '+686', TRUE, 10),
        ('XK', '+383', TRUE, 10),
        ('KW', '+965', TRUE, 10),
        ('KG', '+996', TRUE, 10),
        ('LA', '+856', TRUE, 10),
        ('LV', '+371', TRUE, 10),
        ('LB', '+961', TRUE, 10),
        ('LS', '+266', TRUE, 10),
        ('LR', '+231', TRUE, 10),
        ('LY', '+218', TRUE, 10),
        ('LI', '+423', TRUE, 10),
        ('LT', '+370', TRUE, 10),
        ('LU', '+352', TRUE, 10),
        ('MO', '+853', TRUE, 10),
        ('MG', '+261', TRUE, 10),
        ('MW', '+265', TRUE, 10),
        ('MY', '+60', TRUE, 10),
        ('MV', '+960', TRUE, 10),
        ('ML', '+223', TRUE, 10),
        ('MT', '+356', TRUE, 10),
        ('MH', '+692', TRUE, 10),
        ('MQ', '+596', TRUE, 10),
        ('MR', '+222', TRUE, 10),
        ('MU', '+230', TRUE, 10),
        ('YT', '+262', TRUE, 10),
        ('MX', '+52', TRUE, 10),
        ('FM', '+691', TRUE, 10),
        ('MD', '+373', TRUE, 10),
        ('MC', '+377', TRUE, 10),
        ('MN', '+976', TRUE, 10),
        ('ME', '+382', TRUE, 10),
        ('MS', '+1', TRUE, 10),
        ('MA', '+212', TRUE, 10),
        ('MZ', '+258', TRUE, 10),
        ('MM', '+95', TRUE, 10),
        ('NA', '+264', TRUE, 10),
        ('NR', '+674', TRUE, 10),
        ('NP', '+977', TRUE, 10),
        ('NL', '+31', TRUE, 10),
        ('NC', '+687', TRUE, 10),
        ('NZ', '+64', TRUE, 10),
        ('NI', '+505', TRUE, 10),
        ('NE', '+227', TRUE, 10),
        ('NG', '+234', TRUE, 10),
        ('NU', '+683', TRUE, 10),
        ('NF', '+672', TRUE, 10),
        ('KP', '+850', TRUE, 10),
        ('MK', '+389', TRUE, 10),
        ('MP', '+1', TRUE, 10),
        ('NO', '+47', TRUE, 10),
        ('OM', '+968', TRUE, 10),
        ('PK', '+92', TRUE, 10),
        ('PW', '+680', TRUE, 10),
        ('PS', '+970', TRUE, 10),
        ('PA', '+507', TRUE, 10),
        ('PG', '+675', TRUE, 10),
        ('PY', '+595', TRUE, 10),
        ('PE', '+51', TRUE, 10),
        ('PH', '+63', TRUE, 10),
        ('PN', '+64', TRUE, 10),
        ('PL', '+48', TRUE, 10),
        ('PT', '+351', TRUE, 10),
        ('PR', '+1', TRUE, 10),
        ('QA', '+974', TRUE, 10),
        ('RE', '+262', TRUE, 10),
        ('RO', '+40', TRUE, 10),
        ('RU', '+7', TRUE, 10),
        ('RW', '+250', TRUE, 10),
        ('BL', '+590', TRUE, 10),
        ('SH', '+290', TRUE, 10),
        ('KN', '+1', TRUE, 10),
        ('LC', '+1', TRUE, 10),
        ('MF', '+590', TRUE, 10),
        ('PM', '+508', TRUE, 10),
        ('VC', '+1', TRUE, 10),
        ('WS', '+685', TRUE, 10),
        ('SM', '+378', TRUE, 10),
        ('ST', '+239', TRUE, 10),
        ('SA', '+966', TRUE, 10),
        ('SN', '+221', TRUE, 10),
        ('RS', '+381', TRUE, 10),
        ('SC', '+248', TRUE, 10),
        ('SL', '+232', TRUE, 10),
        ('SG', '+65', TRUE, 10),
        ('SX', '+1', TRUE, 10),
        ('SK', '+421', TRUE, 10),
        ('SI', '+386', TRUE, 10),
        ('SB', '+677', TRUE, 10),
        ('SO', '+252', TRUE, 10),
        ('ZA', '+27', TRUE, 10),
        ('GS', '+500', TRUE, 10),
        ('KR', '+82', TRUE, 10),
        ('SS', '+211', TRUE, 10),
        ('ES', '+34', TRUE, 10),
        ('LK', '+94', TRUE, 10),
        ('SD', '+249', TRUE, 10),
        ('SR', '+597', TRUE, 10),
        ('SJ', '+47', TRUE, 10),
        ('SE', '+46', TRUE, 10),
        ('CH', '+41', TRUE, 10),
        ('SY', '+963', TRUE, 10),
        ('TW', '+886', TRUE, 10),
        ('TJ', '+992', TRUE, 10),
        ('TZ', '+255', TRUE, 10),
        ('TH', '+66', TRUE, 10),
        ('TL', '+670', TRUE, 10),
        ('TG', '+228', TRUE, 10),
        ('TK', '+690', TRUE, 10),
        ('TO', '+676', TRUE, 10),
        ('TT', '+1', TRUE, 10),
        ('TN', '+216', TRUE, 10),
        ('TR', '+90', TRUE, 10),
        ('TM', '+993', TRUE, 10),
        ('TC', '+1', TRUE, 10),
        ('TV', '+688', TRUE, 10),
        ('UG', '+256', TRUE, 10),
        ('UA', '+380', TRUE, 10),
        ('AE', '+971', TRUE, 10),
        ('GB', '+44', TRUE, 10),
        ('UM', '+1', TRUE, 10),
        ('US', '+1', TRUE, 10),
        ('UY', '+598', TRUE, 10),
        ('UZ', '+998', TRUE, 10),
        ('VU', '+678', TRUE, 10),
        ('VE', '+58', TRUE, 10),
        ('VN', '+84', TRUE, 10),
        ('VG', '+1', TRUE, 10),
        ('VI', '+1', TRUE, 10),
        ('WF', '+681', TRUE, 10),
        ('EH', '+212', TRUE, 10),
        ('YE', '+967', TRUE, 10),
        ('ZM', '+260', TRUE, 10),
        ('ZW', '+263', TRUE, 10)
)
INSERT INTO stephen_dcx_country_calling_codes (
    country_id,
    calling_code,
    is_primary,
    sort_order,
    is_active
)
SELECT
    country.id,
    calling_code_seed.calling_code,
    calling_code_seed.is_primary,
    calling_code_seed.sort_order,
    TRUE
FROM calling_code_seed
JOIN stephen_dcx_countries AS country
  ON country.country_code_alpha2 = calling_code_seed.country_code_alpha2
ON CONFLICT (country_id, calling_code) DO UPDATE
SET
    is_primary = EXCLUDED.is_primary,
    sort_order = EXCLUDED.sort_order,
    is_active = TRUE,
    updated_at_ts_ms = ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint);

WITH material_seed(material_key, display_label, synonyms_json, sort_order) AS (
    VALUES
        ('barley', 'Barley', '["barley", "feed barley", "malting barley"]'::jsonb, 10),
        ('cocoa', 'Cocoa', '["cocoa", "cacao", "cocoa beans", "cocoa powder"]'::jsonb, 20),
        ('coffee', 'Coffee', '["coffee", "arabica", "robusta", "green coffee"]'::jsonb, 30),
        ('corn', 'Corn', '["corn", "maize", "yellow corn", "feed corn"]'::jsonb, 40),
        ('cotton', 'Cotton', '["cotton", "cotton lint", "raw cotton"]'::jsonb, 50),
        ('dap', 'DAP', '["dap", "diammonium phosphate", "di-ammonium phosphate"]'::jsonb, 60),
        ('fertilizers', 'Fertilizers', '["fertilizer", "fertilizers", "fertiliser", "fertilisers", "ferts", "fertiliziers"]'::jsonb, 70),
        ('npk', 'NPK', '["npk", "compound fertilizer", "compound fertiliser", "blended fertilizer", "blended fertiliser"]'::jsonb, 80),
        ('oats', 'Oats', '["oat", "oats", "feed oats"]'::jsonb, 90),
        ('oilseeds', 'Oilseeds', '["oilseed", "oilseeds"]'::jsonb, 100),
        ('potash', 'Potash', '["potash", "mop", "sop", "potassium chloride", "potassium sulphate", "potassium sulfate"]'::jsonb, 110),
        ('pulses', 'Pulses', '["pulse", "pulses", "lentils", "chickpeas", "beans", "peas"]'::jsonb, 120),
        ('rapeseed', 'Rapeseed', '["rapeseed", "rapessed", "canola"]'::jsonb, 130),
        ('rice', 'Rice', '["rice", "white rice", "brown rice", "parboiled rice", "basmati", "jasmine rice", "paddy"]'::jsonb, 140),
        ('soybeans', 'Soybeans', '["soybean", "soybeans", "soya", "soy meal", "soybean meal", "soy oil", "soya oil"]'::jsonb, 150),
        ('sugar', 'Sugar', '["sugar", "raw sugar", "white sugar", "icumsa"]'::jsonb, 160),
        ('urea', 'Urea', '["urea", "fertilizer urea", "fertiliser urea", "prilled urea", "granular urea"]'::jsonb, 170),
        ('wheat', 'Wheat', '["wheat", "milling wheat", "feed wheat", "durum"]'::jsonb, 180),
        ('wood_paper_pulp', 'Wood, paper and pulp', '["wood", "timber", "lumber", "paper", "pulp", "wood pulp", "paper pulp"]'::jsonb, 190),
        ('aluminum', 'Aluminum', '["aluminium", "aluminum", "primary aluminum", "primary aluminium", "aluminum ingot", "aluminium ingot", "p1020a"]'::jsonb, 300),
        ('cement_clinker', 'Cement and clinker', '["cement", "clinker", "cement clinker", "portland cement"]'::jsonb, 310),
        ('copper', 'Copper', '["copper", "copper cathode", "copper concentrate"]'::jsonb, 320),
        ('gold', 'Gold', U&'["gold", "gold dore", "gold dor\00E9", "bullion"]'::jsonb, 330),
        ('iron_ore', 'Iron ore', '["iron ore", "iron ore fines", "iron ore pellets", "magnetite", "hematite"]'::jsonb, 340),
        ('lithium', 'Lithium', '["lithium", "lithium carbonate", "lithium hydroxide", "spodumene"]'::jsonb, 350),
        ('nickel', 'Nickel', '["nickel", "nickel ore", "nickel cathode", "nickel sulfate", "nickel sulphate"]'::jsonb, 360),
        ('rare_earths', 'Rare earths', '["rare earth", "rare earths", "rare earth elements", "ree", "neodymium", "praseodymium"]'::jsonb, 370),
        ('steel', 'Steel', '["steel", "steel billet", "steel slab", "rebar", "hot rolled coil", "hrc"]'::jsonb, 380),
        ('coal', 'Coal', '["coal", "thermal coal", "coking coal", "met coal", "metallurgical coal"]'::jsonb, 500),
        ('crude_oil', 'Crude oil', '["crude", "crude oil", "brent", "wti"]'::jsonb, 510),
        ('diesel', 'Diesel', '["diesel", "gasoil", "ultra low sulfur diesel", "ultra low sulphur diesel", "ulsd"]'::jsonb, 520),
        ('fuel_oil', 'Fuel oil', '["fuel oil", "heavy fuel oil", "hfo", "marine fuel"]'::jsonb, 530),
        ('gasoline', 'Gasoline', '["gasoline", "petrol", "naphtha"]'::jsonb, 540),
        ('lng', 'LNG', '["lng", "liquefied natural gas"]'::jsonb, 550),
        ('lpg', 'LPG', '["lpg", "liquefied petroleum gas", "propane", "butane"]'::jsonb, 560),
        ('natural_gas', 'Natural gas', '["natural gas", "pipeline gas", "gas"]'::jsonb, 570),
        ('livestock', 'Livestock', '["livestock", "cattle", "cow", "cows", "calves", "dairy cattle"]'::jsonb, 600)
)
INSERT INTO public.stephen_dcx_trade_interest_material_options (
    material_key,
    display_label,
    synonyms_json,
    sort_order,
    is_active
)
SELECT
    material_seed.material_key,
    material_seed.display_label,
    material_seed.synonyms_json,
    material_seed.sort_order,
    TRUE
FROM material_seed
ON CONFLICT (material_key) DO UPDATE
SET
    display_label = EXCLUDED.display_label,
    synonyms_json = EXCLUDED.synonyms_json,
    sort_order = EXCLUDED.sort_order,
    is_active = TRUE,
    updated_at_ts_ms = ((EXTRACT(EPOCH FROM clock_timestamp()) * 1000::numeric)::bigint);

COMMIT;
