-- DCX Slice 1 workflow/trades/topics app UX strings.
-- Run this in local and live after the Slice 1 code deploy so the new Send,
-- Messages, Trades, and Topics UI copy resolves through the shared app UX bundle.

WITH language_string_maps(language_code, strings_json) AS (
    VALUES
    ('en', $json$
{
  "messages_compose_progress_routing_title": "Routing workflow...",
  "messages_compose_progress_routing_body": "DCX is deciding whether this is a trade, market topic, other message, or prohibited content.",
  "messages_compose_progress_routed_title": "Workflow routed.",
  "messages_compose_progress_routing_complete_body": "Workflow routing is complete.",
  "messages_compose_progress_message_blocked_title": "Message blocked",
  "messages_compose_progress_open_message_default_body": "Open the message from Messages when you are ready.",
  "messages_compose_progress_open_outputs_body": "Open the message or jump straight to the created trade/topic output.",
  "messages_compose_progress_open_other_body": "Open the message to review the stored Other item.",
  "messages_compose_progress_stored_for_review_body": "Stored in Messages for review.",
  "messages_compose_progress_routed_as_prefix": "Routed as",
  "messages_compose_progress_trade_candidate_singular": "trade candidate",
  "messages_compose_progress_trade_candidate_plural": "trade candidates",
  "messages_compose_progress_market_topic_singular": "market topic",
  "messages_compose_progress_market_topic_plural": "market topics",
  "messages_compose_progress_other_label": "Other",
  "messages_compose_outcome_open_message": "Open message",
  "messages_compose_outcome_open_trade": "Open trade",
  "messages_compose_outcome_open_topic": "Open topic",
  "messages_workflow_items_label": "Workflow items",
  "messages_workflow_item_fallback": "Workflow item",
  "messages_workflow_action_needed_label": "Action needed",
  "messages_workflow_open_trade": "Open trade",
  "messages_workflow_open_topic": "Open topic",
  "messages_workflow_retry_button": "Retry workflow processing",
  "trades_search_placeholder": "Search trades...",
  "trades_filter_all_sides": "All sides",
  "trades_filter_all_states": "All states",
  "trades_filter_all_materials": "All materials",
  "trades_loading": "Loading trades...",
  "trades_error_title": "Trades could not load",
  "trades_error_suggested_action": "Retry after confirming the backend is reachable.",
  "trades_empty": "No structured trades match these filters.",
  "trades_table_column_trade": "Trade",
  "trades_table_column_side": "Side",
  "trades_table_column_amount": "Amount",
  "trades_table_column_unit": "Unit",
  "trades_table_column_thing": "Thing",
  "trades_table_column_unit_price": "Unit price",
  "trades_table_column_origin": "Origin",
  "trades_table_column_state": "State",
  "trades_table_column_updated": "Updated",
  "trades_detail_empty": "Choose a trade candidate to inspect, confirm, or correct it.",
  "trades_detail_summary_label": "Summary",
  "trades_save_status_label": "Save status",
  "trades_trade_details_label": "Trade details",
  "trades_trade_state_label": "Trade state",
  "trades_trade_side_label": "Trade side",
  "trades_material_label": "Material",
  "trades_quantity_value_label": "Quantity",
  "trades_quantity_unit_label": "Units",
  "trades_price_mode_label": "Price mode",
  "trades_price_value_label": "Price per unit",
  "trades_price_unit_basis_label": "Units",
  "trades_currency_code_label": "Currency",
  "trades_total_price_value_label": "Total price",
  "trades_destination_label": "Destination",
  "trades_shipping_method_label": "Shipping method",
  "trades_incoterm_label": "Incoterm",
  "trades_delivery_window_start_label": "Delivery window start",
  "trades_delivery_window_end_label": "Delivery window end",
  "trades_date_not_set_label": "Choose date",
  "trades_quality_summary_label": "Quality summary",
  "trades_payment_terms_summary_label": "Payment terms summary",
  "trades_version_history_label": "Version history",
  "trades_saved_shape_singular": "saved trade shape",
  "trades_saved_shape_plural": "saved trade shapes",
  "trades_version_label": "Version",
  "trades_current_label": "Current",
  "trades_state_label": "State:",
  "trades_material_value_label": "Material:",
  "trades_quantity_value_summary_label": "Quantity:",
  "trades_price_value_summary_label": "Price:",
  "trades_total_value_summary_label": "Total:",
  "trades_route_label": "Route:",
  "trades_raw_material_label": "Raw material",
  "trades_raw_quantity_label": "Raw quantity",
  "trades_raw_price_label": "Raw price",
  "trades_raw_origin_label": "Raw origin",
  "trades_raw_destination_label": "Raw destination",
  "trades_trade_notes_label": "Trade notes",
  "trades_source_message_label": "Source message",
  "trades_action_needed_label": "Action needed",
  "trades_ready_label": "Ready",
  "trades_save_details_button": "Save details",
  "trades_saving_button": "Saving...",
  "trades_saved_button": "Saved",
  "trades_not_specified_label": "Not specified",
  "trades_price_not_specified_label": "Price not specified",
  "trades_current_shape_captured": "The current trade shape has been captured.",
  "trades_open_details_prefix": "Open details:",
  "trades_autosave_prefix": "Autosave in",
  "trades_state_draft": "Draft",
  "trades_state_needs_more_detail": "Needs details",
  "trades_state_pending_confirmation": "Pending confirmation",
  "trades_state_confirmed": "Confirmed",
  "trades_state_under_revision": "Under revision",
  "trades_state_rejected": "Rejected",
  "trades_side_sell": "Sell",
  "trades_side_buy": "Buy",
  "trades_price_mode_fixed": "Fixed",
  "trades_price_mode_indicative": "Indicative",
  "trades_price_mode_negotiable": "Negotiable",
  "trades_price_mode_index_linked": "Index linked",
  "topics_search_placeholder": "Search topics...",
  "topics_filter_all_statuses": "All statuses",
  "topics_filter_all_sources": "All sources",
  "topics_loading": "Loading topics...",
  "topics_error_title": "Topics could not load",
  "topics_error_suggested_action": "Retry after confirming the backend is reachable.",
  "topics_empty": "No market topics match these filters.",
  "topics_table_column_topic": "Topic",
  "topics_table_column_tags": "Tags",
  "topics_table_column_status": "Status",
  "topics_table_column_source": "Source",
  "topics_table_column_updated": "Updated",
  "topics_detail_empty": "Choose a topic to inspect its seeded AI response.",
  "topics_detail_topic_label": "Topic",
  "topics_detail_tags_label": "Tags",
  "topics_detail_opening_ai_response_label": "Opening AI response",
  "topics_status_open": "Open",
  "topics_status_closed": "Closed",
  "topics_status_archived": "Archived"
}
$json$::jsonb),
    ('es', $json$
{
  "messages_compose_progress_routing_title": "Clasificando flujo...",
  "messages_compose_progress_routing_body": "DCX decide si esto es una operación, un tema de mercado, otro mensaje o contenido prohibido.",
  "messages_compose_progress_routed_title": "Flujo clasificado.",
  "messages_compose_progress_routing_complete_body": "La clasificación del flujo se ha completado.",
  "messages_compose_progress_message_blocked_title": "Mensaje bloqueado",
  "messages_compose_progress_open_message_default_body": "Abre el mensaje desde Mensajes cuando quieras.",
  "messages_compose_progress_open_outputs_body": "Abre el mensaje o salta directamente a la operación o tema creado.",
  "messages_compose_progress_open_other_body": "Abre el mensaje para revisar el elemento guardado en Otros.",
  "messages_compose_progress_stored_for_review_body": "Guardado en Mensajes para revisión.",
  "messages_compose_progress_routed_as_prefix": "Clasificado como",
  "messages_compose_progress_trade_candidate_singular": "candidato de operación",
  "messages_compose_progress_trade_candidate_plural": "candidatos de operación",
  "messages_compose_progress_market_topic_singular": "tema de mercado",
  "messages_compose_progress_market_topic_plural": "temas de mercado",
  "messages_compose_progress_other_label": "Otro",
  "messages_compose_outcome_open_message": "Abrir mensaje",
  "messages_compose_outcome_open_trade": "Abrir operación",
  "messages_compose_outcome_open_topic": "Abrir tema",
  "messages_workflow_items_label": "Elementos del flujo",
  "messages_workflow_item_fallback": "Elemento del flujo",
  "messages_workflow_action_needed_label": "Requiere atención",
  "messages_workflow_open_trade": "Abrir operación",
  "messages_workflow_open_topic": "Abrir tema",
  "messages_workflow_retry_button": "Reintentar clasificación del flujo",
  "trades_search_placeholder": "Buscar operaciones...",
  "trades_filter_all_sides": "Todos los lados",
  "trades_filter_all_states": "Todos los estados",
  "trades_filter_all_materials": "Todos los materiales",
  "trades_loading": "Cargando operaciones...",
  "trades_error_title": "No se pudieron cargar las operaciones",
  "trades_error_suggested_action": "Reintenta después de confirmar que el backend está disponible.",
  "trades_empty": "Ninguna operación estructurada coincide con estos filtros.",
  "trades_table_column_trade": "Operación",
  "trades_table_column_side": "Lado",
  "trades_table_column_amount": "Cantidad",
  "trades_table_column_unit": "Unidad",
  "trades_table_column_thing": "Producto",
  "trades_table_column_unit_price": "Precio unitario",
  "trades_table_column_origin": "Origen",
  "trades_table_column_state": "Estado",
  "trades_table_column_updated": "Actualizado",
  "trades_detail_empty": "Elige una operación candidata para revisarla, confirmarla o corregirla.",
  "trades_detail_summary_label": "Resumen",
  "trades_save_status_label": "Estado de guardado",
  "trades_trade_details_label": "Detalles de la operación",
  "trades_trade_state_label": "Estado de la operación",
  "trades_trade_side_label": "Lado de la operación",
  "trades_material_label": "Material",
  "trades_quantity_value_label": "Cantidad",
  "trades_quantity_unit_label": "Unidades",
  "trades_price_mode_label": "Modo de precio",
  "trades_price_value_label": "Precio por unidad",
  "trades_price_unit_basis_label": "Unidades",
  "trades_currency_code_label": "Moneda",
  "trades_total_price_value_label": "Precio total",
  "trades_destination_label": "Destino",
  "trades_shipping_method_label": "Método de envío",
  "trades_incoterm_label": "Incoterm",
  "trades_delivery_window_start_label": "Inicio de entrega",
  "trades_delivery_window_end_label": "Fin de entrega",
  "trades_date_not_set_label": "Elegir fecha",
  "trades_quality_summary_label": "Resumen de calidad",
  "trades_payment_terms_summary_label": "Resumen de pago",
  "trades_version_history_label": "Historial de versiones",
  "trades_saved_shape_singular": "forma guardada de la operación",
  "trades_saved_shape_plural": "formas guardadas de la operación",
  "trades_version_label": "Versión",
  "trades_current_label": "Actual",
  "trades_state_label": "Estado:",
  "trades_material_value_label": "Material:",
  "trades_quantity_value_summary_label": "Cantidad:",
  "trades_price_value_summary_label": "Precio:",
  "trades_total_value_summary_label": "Total:",
  "trades_route_label": "Ruta:",
  "trades_raw_material_label": "Material original",
  "trades_raw_quantity_label": "Cantidad original",
  "trades_raw_price_label": "Precio original",
  "trades_raw_origin_label": "Origen original",
  "trades_raw_destination_label": "Destino original",
  "trades_trade_notes_label": "Notas de la operación",
  "trades_source_message_label": "Mensaje fuente",
  "trades_action_needed_label": "Requiere atención",
  "trades_ready_label": "Listo",
  "trades_save_details_button": "Guardar detalles",
  "trades_saving_button": "Guardando...",
  "trades_saved_button": "Guardado",
  "trades_not_specified_label": "No especificado",
  "trades_price_not_specified_label": "Precio no especificado",
  "trades_current_shape_captured": "La forma actual de la operación se ha guardado.",
  "trades_open_details_prefix": "Detalles abiertos:",
  "trades_autosave_prefix": "Autoguardado en",
  "trades_state_draft": "Borrador",
  "trades_state_needs_more_detail": "Necesita detalles",
  "trades_state_pending_confirmation": "Pendiente de confirmación",
  "trades_state_confirmed": "Confirmada",
  "trades_state_under_revision": "En revisión",
  "trades_state_rejected": "Rechazada",
  "trades_side_sell": "Venta",
  "trades_side_buy": "Compra",
  "trades_price_mode_fixed": "Fijo",
  "trades_price_mode_indicative": "Indicativo",
  "trades_price_mode_negotiable": "Negociable",
  "trades_price_mode_index_linked": "Ligado a índice",
  "topics_search_placeholder": "Buscar temas...",
  "topics_filter_all_statuses": "Todos los estados",
  "topics_filter_all_sources": "Todas las fuentes",
  "topics_loading": "Cargando temas...",
  "topics_error_title": "No se pudieron cargar los temas",
  "topics_error_suggested_action": "Reintenta después de confirmar que el backend está disponible.",
  "topics_empty": "Ningún tema de mercado coincide con estos filtros.",
  "topics_table_column_topic": "Tema",
  "topics_table_column_tags": "Etiquetas",
  "topics_table_column_status": "Estado",
  "topics_table_column_source": "Fuente",
  "topics_table_column_updated": "Actualizado",
  "topics_detail_empty": "Elige un tema para revisar su primera respuesta de IA.",
  "topics_detail_topic_label": "Tema",
  "topics_detail_tags_label": "Etiquetas",
  "topics_detail_opening_ai_response_label": "Primera respuesta de IA",
  "topics_status_open": "Abierto",
  "topics_status_closed": "Cerrado",
  "topics_status_archived": "Archivado"
}
$json$::jsonb),
    ('fr', $json$
{
  "messages_compose_progress_routing_title": "Routage du flux...",
  "messages_compose_progress_routing_body": "DCX détermine s'il s'agit d'une transaction, d'un sujet de marché, d'un autre message ou d'un contenu interdit.",
  "messages_compose_progress_routed_title": "Flux routé.",
  "messages_compose_progress_routing_complete_body": "Le routage du flux est terminé.",
  "messages_compose_progress_message_blocked_title": "Message bloqué",
  "messages_compose_progress_open_message_default_body": "Ouvrez le message dans Messages quand vous êtes prêt.",
  "messages_compose_progress_open_outputs_body": "Ouvrez le message ou accédez directement à la transaction ou au sujet créé.",
  "messages_compose_progress_open_other_body": "Ouvrez le message pour examiner l'élément enregistré dans Autre.",
  "messages_compose_progress_stored_for_review_body": "Enregistré dans Messages pour examen.",
  "messages_compose_progress_routed_as_prefix": "Routé comme",
  "messages_compose_progress_trade_candidate_singular": "transaction candidate",
  "messages_compose_progress_trade_candidate_plural": "transactions candidates",
  "messages_compose_progress_market_topic_singular": "sujet de marché",
  "messages_compose_progress_market_topic_plural": "sujets de marché",
  "messages_compose_progress_other_label": "Autre",
  "messages_compose_outcome_open_message": "Ouvrir le message",
  "messages_compose_outcome_open_trade": "Ouvrir la transaction",
  "messages_compose_outcome_open_topic": "Ouvrir le sujet",
  "messages_workflow_items_label": "Éléments du flux",
  "messages_workflow_item_fallback": "Élément du flux",
  "messages_workflow_action_needed_label": "Action requise",
  "messages_workflow_open_trade": "Ouvrir la transaction",
  "messages_workflow_open_topic": "Ouvrir le sujet",
  "messages_workflow_retry_button": "Relancer le traitement du flux",
  "trades_search_placeholder": "Rechercher des transactions...",
  "trades_filter_all_sides": "Tous les sens",
  "trades_filter_all_states": "Tous les états",
  "trades_filter_all_materials": "Toutes les matières",
  "trades_loading": "Chargement des transactions...",
  "trades_error_title": "Les transactions n'ont pas pu être chargées",
  "trades_error_suggested_action": "Réessayez après avoir confirmé que le backend est accessible.",
  "trades_empty": "Aucune transaction structurée ne correspond à ces filtres.",
  "trades_table_column_trade": "Transaction",
  "trades_table_column_side": "Sens",
  "trades_table_column_amount": "Quantité",
  "trades_table_column_unit": "Unité",
  "trades_table_column_thing": "Produit",
  "trades_table_column_unit_price": "Prix unitaire",
  "trades_table_column_origin": "Origine",
  "trades_table_column_state": "État",
  "trades_table_column_updated": "Mis à jour",
  "trades_detail_empty": "Choisissez une transaction candidate à examiner, confirmer ou corriger.",
  "trades_detail_summary_label": "Résumé",
  "trades_save_status_label": "État d'enregistrement",
  "trades_trade_details_label": "Détails de la transaction",
  "trades_trade_state_label": "État de la transaction",
  "trades_trade_side_label": "Sens de la transaction",
  "trades_material_label": "Matière",
  "trades_quantity_value_label": "Quantité",
  "trades_quantity_unit_label": "Unités",
  "trades_price_mode_label": "Mode de prix",
  "trades_price_value_label": "Prix par unité",
  "trades_price_unit_basis_label": "Unités",
  "trades_currency_code_label": "Devise",
  "trades_total_price_value_label": "Prix total",
  "trades_destination_label": "Destination",
  "trades_shipping_method_label": "Mode d'expédition",
  "trades_incoterm_label": "Incoterm",
  "trades_delivery_window_start_label": "Début de livraison",
  "trades_delivery_window_end_label": "Fin de livraison",
  "trades_date_not_set_label": "Choisir une date",
  "trades_quality_summary_label": "Résumé qualité",
  "trades_payment_terms_summary_label": "Résumé des conditions de paiement",
  "trades_version_history_label": "Historique des versions",
  "trades_saved_shape_singular": "forme de transaction enregistrée",
  "trades_saved_shape_plural": "formes de transaction enregistrées",
  "trades_version_label": "Version",
  "trades_current_label": "Actuelle",
  "trades_state_label": "État :",
  "trades_material_value_label": "Matière :",
  "trades_quantity_value_summary_label": "Quantité :",
  "trades_price_value_summary_label": "Prix :",
  "trades_total_value_summary_label": "Total :",
  "trades_route_label": "Route :",
  "trades_raw_material_label": "Matière brute",
  "trades_raw_quantity_label": "Quantité brute",
  "trades_raw_price_label": "Prix brut",
  "trades_raw_origin_label": "Origine brute",
  "trades_raw_destination_label": "Destination brute",
  "trades_trade_notes_label": "Notes de transaction",
  "trades_source_message_label": "Message source",
  "trades_action_needed_label": "Action requise",
  "trades_ready_label": "Prêt",
  "trades_save_details_button": "Enregistrer les détails",
  "trades_saving_button": "Enregistrement...",
  "trades_saved_button": "Enregistré",
  "trades_not_specified_label": "Non spécifié",
  "trades_price_not_specified_label": "Prix non spécifié",
  "trades_current_shape_captured": "La forme actuelle de la transaction a été enregistrée.",
  "trades_open_details_prefix": "Détails ouverts :",
  "trades_autosave_prefix": "Enregistrement auto dans",
  "trades_state_draft": "Brouillon",
  "trades_state_needs_more_detail": "Détails requis",
  "trades_state_pending_confirmation": "Confirmation en attente",
  "trades_state_confirmed": "Confirmée",
  "trades_state_under_revision": "En révision",
  "trades_state_rejected": "Rejetée",
  "trades_side_sell": "Vente",
  "trades_side_buy": "Achat",
  "trades_price_mode_fixed": "Fixe",
  "trades_price_mode_indicative": "Indicatif",
  "trades_price_mode_negotiable": "Négociable",
  "trades_price_mode_index_linked": "Lié à un indice",
  "topics_search_placeholder": "Rechercher des sujets...",
  "topics_filter_all_statuses": "Tous les états",
  "topics_filter_all_sources": "Toutes les sources",
  "topics_loading": "Chargement des sujets...",
  "topics_error_title": "Les sujets n'ont pas pu être chargés",
  "topics_error_suggested_action": "Réessayez après avoir confirmé que le backend est accessible.",
  "topics_empty": "Aucun sujet de marché ne correspond à ces filtres.",
  "topics_table_column_topic": "Sujet",
  "topics_table_column_tags": "Tags",
  "topics_table_column_status": "État",
  "topics_table_column_source": "Source",
  "topics_table_column_updated": "Mis à jour",
  "topics_detail_empty": "Choisissez un sujet pour examiner sa première réponse IA.",
  "topics_detail_topic_label": "Sujet",
  "topics_detail_tags_label": "Tags",
  "topics_detail_opening_ai_response_label": "Première réponse IA",
  "topics_status_open": "Ouvert",
  "topics_status_closed": "Fermé",
  "topics_status_archived": "Archivé"
}
$json$::jsonb),
    ('de', $json$
{
  "messages_compose_progress_routing_title": "Workflow wird zugeordnet...",
  "messages_compose_progress_routing_body": "DCX entscheidet, ob dies ein Handel, ein Marktthema, eine andere Nachricht oder verbotener Inhalt ist.",
  "messages_compose_progress_routed_title": "Workflow zugeordnet.",
  "messages_compose_progress_routing_complete_body": "Die Workflow-Zuordnung ist abgeschlossen.",
  "messages_compose_progress_message_blocked_title": "Nachricht blockiert",
  "messages_compose_progress_open_message_default_body": "Öffnen Sie die Nachricht in Nachrichten, wenn Sie bereit sind.",
  "messages_compose_progress_open_outputs_body": "Öffnen Sie die Nachricht oder springen Sie direkt zum erstellten Handel oder Thema.",
  "messages_compose_progress_open_other_body": "Öffnen Sie die Nachricht, um den gespeicherten Sonstiges-Eintrag zu prüfen.",
  "messages_compose_progress_stored_for_review_body": "In Nachrichten zur Prüfung gespeichert.",
  "messages_compose_progress_routed_as_prefix": "Zugeordnet als",
  "messages_compose_progress_trade_candidate_singular": "Handelskandidat",
  "messages_compose_progress_trade_candidate_plural": "Handelskandidaten",
  "messages_compose_progress_market_topic_singular": "Marktthema",
  "messages_compose_progress_market_topic_plural": "Marktthemen",
  "messages_compose_progress_other_label": "Sonstiges",
  "messages_compose_outcome_open_message": "Nachricht öffnen",
  "messages_compose_outcome_open_trade": "Handel öffnen",
  "messages_compose_outcome_open_topic": "Thema öffnen",
  "messages_workflow_items_label": "Workflow-Elemente",
  "messages_workflow_item_fallback": "Workflow-Element",
  "messages_workflow_action_needed_label": "Aktion erforderlich",
  "messages_workflow_open_trade": "Handel öffnen",
  "messages_workflow_open_topic": "Thema öffnen",
  "messages_workflow_retry_button": "Workflow-Verarbeitung wiederholen",
  "trades_search_placeholder": "Handel suchen...",
  "trades_filter_all_sides": "Alle Seiten",
  "trades_filter_all_states": "Alle Status",
  "trades_filter_all_materials": "Alle Materialien",
  "trades_loading": "Handel werden geladen...",
  "trades_error_title": "Handel konnten nicht geladen werden",
  "trades_error_suggested_action": "Erneut versuchen, nachdem das Backend erreichbar ist.",
  "trades_empty": "Keine strukturierten Handel passen zu diesen Filtern.",
  "trades_table_column_trade": "Handel",
  "trades_table_column_side": "Seite",
  "trades_table_column_amount": "Menge",
  "trades_table_column_unit": "Einheit",
  "trades_table_column_thing": "Ware",
  "trades_table_column_unit_price": "Einheitspreis",
  "trades_table_column_origin": "Ursprung",
  "trades_table_column_state": "Status",
  "trades_table_column_updated": "Aktualisiert",
  "trades_detail_empty": "Wählen Sie einen Handelskandidaten aus, um ihn zu prüfen, zu bestätigen oder zu korrigieren.",
  "trades_detail_summary_label": "Zusammenfassung",
  "trades_save_status_label": "Speicherstatus",
  "trades_trade_details_label": "Handelsdetails",
  "trades_trade_state_label": "Handelsstatus",
  "trades_trade_side_label": "Handelsseite",
  "trades_material_label": "Material",
  "trades_quantity_value_label": "Menge",
  "trades_quantity_unit_label": "Einheiten",
  "trades_price_mode_label": "Preismodus",
  "trades_price_value_label": "Preis pro Einheit",
  "trades_price_unit_basis_label": "Einheiten",
  "trades_currency_code_label": "Währung",
  "trades_total_price_value_label": "Gesamtpreis",
  "trades_destination_label": "Ziel",
  "trades_shipping_method_label": "Versandart",
  "trades_incoterm_label": "Incoterm",
  "trades_delivery_window_start_label": "Lieferfenster Beginn",
  "trades_delivery_window_end_label": "Lieferfenster Ende",
  "trades_date_not_set_label": "Datum wählen",
  "trades_quality_summary_label": "Qualitätsübersicht",
  "trades_payment_terms_summary_label": "Zahlungsbedingungen",
  "trades_version_history_label": "Versionsverlauf",
  "trades_saved_shape_singular": "gespeicherte Handelsform",
  "trades_saved_shape_plural": "gespeicherte Handelsformen",
  "trades_version_label": "Version",
  "trades_current_label": "Aktuell",
  "trades_state_label": "Status:",
  "trades_material_value_label": "Material:",
  "trades_quantity_value_summary_label": "Menge:",
  "trades_price_value_summary_label": "Preis:",
  "trades_total_value_summary_label": "Gesamt:",
  "trades_route_label": "Route:",
  "trades_raw_material_label": "Rohmaterial",
  "trades_raw_quantity_label": "Rohmenge",
  "trades_raw_price_label": "Rohpreis",
  "trades_raw_origin_label": "Rohursprung",
  "trades_raw_destination_label": "Rohziel",
  "trades_trade_notes_label": "Handelsnotizen",
  "trades_source_message_label": "Quellnachricht",
  "trades_action_needed_label": "Aktion erforderlich",
  "trades_ready_label": "Bereit",
  "trades_save_details_button": "Details speichern",
  "trades_saving_button": "Speichern...",
  "trades_saved_button": "Gespeichert",
  "trades_not_specified_label": "Nicht angegeben",
  "trades_price_not_specified_label": "Preis nicht angegeben",
  "trades_current_shape_captured": "Die aktuelle Handelsform wurde gespeichert.",
  "trades_open_details_prefix": "Offene Details:",
  "trades_autosave_prefix": "Autospeichern in",
  "trades_state_draft": "Entwurf",
  "trades_state_needs_more_detail": "Details erforderlich",
  "trades_state_pending_confirmation": "Bestätigung ausstehend",
  "trades_state_confirmed": "Bestätigt",
  "trades_state_under_revision": "In Überarbeitung",
  "trades_state_rejected": "Abgelehnt",
  "trades_side_sell": "Verkauf",
  "trades_side_buy": "Kauf",
  "trades_price_mode_fixed": "Fest",
  "trades_price_mode_indicative": "Indikativ",
  "trades_price_mode_negotiable": "Verhandelbar",
  "trades_price_mode_index_linked": "Indexgebunden",
  "topics_search_placeholder": "Themen suchen...",
  "topics_filter_all_statuses": "Alle Status",
  "topics_filter_all_sources": "Alle Quellen",
  "topics_loading": "Themen werden geladen...",
  "topics_error_title": "Themen konnten nicht geladen werden",
  "topics_error_suggested_action": "Erneut versuchen, nachdem das Backend erreichbar ist.",
  "topics_empty": "Keine Marktthemen passen zu diesen Filtern.",
  "topics_table_column_topic": "Thema",
  "topics_table_column_tags": "Tags",
  "topics_table_column_status": "Status",
  "topics_table_column_source": "Quelle",
  "topics_table_column_updated": "Aktualisiert",
  "topics_detail_empty": "Wählen Sie ein Thema aus, um die erste KI-Antwort zu prüfen.",
  "topics_detail_topic_label": "Thema",
  "topics_detail_tags_label": "Tags",
  "topics_detail_opening_ai_response_label": "Erste KI-Antwort",
  "topics_status_open": "Offen",
  "topics_status_closed": "Geschlossen",
  "topics_status_archived": "Archiviert"
}
$json$::jsonb)
),
desired_strings AS (
    SELECT
        'app_account_page'::text AS string_group,
        key_value.key AS string_key,
        language_string_maps.language_code,
        key_value.value AS text_value,
        (language_string_maps.language_code = 'en') AS is_original
    FROM language_string_maps
    CROSS JOIN LATERAL jsonb_each_text(language_string_maps.strings_json) AS key_value
),
language_rows AS (
    SELECT id, language_code
    FROM stephen_dcx_languages
    WHERE language_code IN ('en', 'es', 'fr', 'de')
),
english_live_originals AS (
    SELECT
        originals.id,
        originals.string_group,
        originals.string_key
    FROM stephen_dcx_ux_strings originals
    JOIN language_rows english_language
      ON english_language.id = originals.language_id
     AND english_language.language_code = 'en'
    WHERE originals.is_original = TRUE
      AND originals.is_live = TRUE
),
updated_live_rows AS (
    UPDATE stephen_dcx_ux_strings existing
    SET text = desired_strings.text_value
    FROM desired_strings
    JOIN language_rows target_language
      ON target_language.language_code = desired_strings.language_code
    WHERE existing.string_group = desired_strings.string_group
      AND existing.string_key = desired_strings.string_key
      AND existing.language_id = target_language.id
      AND existing.is_live = TRUE
      AND existing.text <> desired_strings.text_value
    RETURNING existing.id
),
inserted_english_originals AS (
    INSERT INTO stephen_dcx_ux_strings
    (string_group, string_key, language_id, text, is_original, is_live, version_of_id, translation_of_id)
    SELECT
        desired_strings.string_group,
        desired_strings.string_key,
        english_language.id,
        desired_strings.text_value,
        TRUE,
        TRUE,
        NULL,
        NULL
    FROM desired_strings
    JOIN language_rows english_language
      ON english_language.language_code = desired_strings.language_code
    WHERE desired_strings.language_code = 'en'
      AND desired_strings.is_original = TRUE
      AND NOT EXISTS (
          SELECT 1
          FROM stephen_dcx_ux_strings existing
          WHERE existing.string_group = desired_strings.string_group
            AND existing.string_key = desired_strings.string_key
            AND existing.language_id = english_language.id
            AND existing.is_original = TRUE
            AND existing.is_live = TRUE
      )
    RETURNING id, string_group, string_key
),
english_live_originals_after_seed AS (
    SELECT id, string_group, string_key
    FROM english_live_originals
    UNION ALL
    SELECT id, string_group, string_key
    FROM inserted_english_originals
)
INSERT INTO stephen_dcx_ux_strings
(string_group, string_key, language_id, text, is_original, is_live, version_of_id, translation_of_id)
SELECT
    desired_strings.string_group,
    desired_strings.string_key,
    target_language.id,
    desired_strings.text_value,
    FALSE,
    TRUE,
    NULL,
    english_live_originals_after_seed.id
FROM desired_strings
JOIN language_rows target_language
  ON target_language.language_code = desired_strings.language_code
JOIN english_live_originals_after_seed
  ON english_live_originals_after_seed.string_group = desired_strings.string_group
 AND english_live_originals_after_seed.string_key = desired_strings.string_key
WHERE desired_strings.language_code <> 'en'
  AND NOT EXISTS (
      SELECT 1
      FROM stephen_dcx_ux_strings existing
      WHERE existing.string_group = desired_strings.string_group
        AND existing.string_key = desired_strings.string_key
        AND existing.language_id = target_language.id
        AND existing.is_live = TRUE
  );
