-- DCX MVP Slice 2/3 spine: market visibility, public/forum projections, and interaction threads.
-- Run after Slice 1 trade/topic workflow and trade-version migrations.

ALTER TABLE stephen_dcx_trades
ADD COLUMN IF NOT EXISTS visibility_status text NOT NULL DEFAULT 'private',
ADD COLUMN IF NOT EXISTS visibility_updated_at_ts_ms bigint,
ADD COLUMN IF NOT EXISTS visibility_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE stephen_dcx_market_topics
ADD COLUMN IF NOT EXISTS visibility_status text NOT NULL DEFAULT 'private',
ADD COLUMN IF NOT EXISTS visibility_updated_at_ts_ms bigint,
ADD COLUMN IF NOT EXISTS visibility_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'stephen_dcx_trades_visibility_status_check'
    ) THEN
        ALTER TABLE stephen_dcx_trades
        ADD CONSTRAINT stephen_dcx_trades_visibility_status_check
        CHECK (visibility_status IN ('private', 'shareable', 'public'));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'stephen_dcx_market_topics_visibility_status_check'
    ) THEN
        ALTER TABLE stephen_dcx_market_topics
        ADD CONSTRAINT stephen_dcx_market_topics_visibility_status_check
        CHECK (visibility_status IN ('private', 'shareable', 'public'));
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS stephen_dcx_trade_publications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_id bigint NOT NULL REFERENCES stephen_dcx_trades(id) ON DELETE CASCADE,
    owner_user_id bigint NOT NULL REFERENCES stephen_dcx_users(id) ON DELETE CASCADE,
    published_trade_version_id bigint REFERENCES stephen_dcx_trade_versions(id) ON DELETE SET NULL,
    visibility_status text NOT NULL DEFAULT 'shareable',
    publication_status text NOT NULL DEFAULT 'active',
    public_reference_code text NOT NULL,
    share_token text,
    published_summary_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    publication_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL,
    updated_at_ts_ms bigint NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS stephen_dcx_trade_publications_public_reference_code_key
ON stephen_dcx_trade_publications(public_reference_code);

CREATE UNIQUE INDEX IF NOT EXISTS stephen_dcx_trade_publications_share_token_key
ON stephen_dcx_trade_publications(share_token)
WHERE share_token IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS stephen_dcx_trade_publications_active_trade_key
ON stephen_dcx_trade_publications(trade_id)
WHERE publication_status = 'active';

CREATE INDEX IF NOT EXISTS stephen_dcx_trade_publications_market_catalog_idx
ON stephen_dcx_trade_publications(visibility_status, publication_status, updated_at_ts_ms DESC, id DESC);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'stephen_dcx_trade_publications_visibility_status_check'
    ) THEN
        ALTER TABLE stephen_dcx_trade_publications
        ADD CONSTRAINT stephen_dcx_trade_publications_visibility_status_check
        CHECK (visibility_status IN ('shareable', 'public'));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'stephen_dcx_trade_publications_publication_status_check'
    ) THEN
        ALTER TABLE stephen_dcx_trade_publications
        ADD CONSTRAINT stephen_dcx_trade_publications_publication_status_check
        CHECK (publication_status IN ('active', 'archived', 'withdrawn'));
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS stephen_dcx_forum_posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_market_topic_id bigint NOT NULL REFERENCES stephen_dcx_market_topics(id) ON DELETE CASCADE,
    owner_user_id bigint NOT NULL REFERENCES stephen_dcx_users(id) ON DELETE CASCADE,
    source_message_id bigint REFERENCES stephen_dcx_contact_messages(id) ON DELETE SET NULL,
    visibility_status text NOT NULL DEFAULT 'shareable',
    forum_post_status text NOT NULL DEFAULT 'open',
    public_reference_code text NOT NULL,
    share_token text,
    forum_title text NOT NULL DEFAULT '',
    forum_body_text text NOT NULL DEFAULT '',
    forum_tags_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    forum_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL,
    updated_at_ts_ms bigint NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS stephen_dcx_forum_posts_public_reference_code_key
ON stephen_dcx_forum_posts(public_reference_code);

CREATE UNIQUE INDEX IF NOT EXISTS stephen_dcx_forum_posts_share_token_key
ON stephen_dcx_forum_posts(share_token)
WHERE share_token IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS stephen_dcx_forum_posts_active_topic_key
ON stephen_dcx_forum_posts(source_market_topic_id)
WHERE forum_post_status IN ('open', 'closed');

CREATE INDEX IF NOT EXISTS stephen_dcx_forum_posts_market_catalog_idx
ON stephen_dcx_forum_posts(visibility_status, forum_post_status, updated_at_ts_ms DESC, id DESC);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'stephen_dcx_forum_posts_visibility_status_check'
    ) THEN
        ALTER TABLE stephen_dcx_forum_posts
        ADD CONSTRAINT stephen_dcx_forum_posts_visibility_status_check
        CHECK (visibility_status IN ('shareable', 'public'));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'stephen_dcx_forum_posts_forum_post_status_check'
    ) THEN
        ALTER TABLE stephen_dcx_forum_posts
        ADD CONSTRAINT stephen_dcx_forum_posts_forum_post_status_check
        CHECK (forum_post_status IN ('open', 'closed', 'archived', 'withdrawn'));
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS stephen_dcx_forum_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forum_post_id bigint NOT NULL REFERENCES stephen_dcx_forum_posts(id) ON DELETE CASCADE,
    author_user_id bigint NOT NULL REFERENCES stephen_dcx_users(id) ON DELETE CASCADE,
    source_contact_message_id bigint REFERENCES stephen_dcx_contact_messages(id) ON DELETE SET NULL,
    comment_text text NOT NULL DEFAULT '',
    language_code text NOT NULL DEFAULT 'en',
    comment_summary_text text NOT NULL DEFAULT '',
    comment_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL,
    updated_at_ts_ms bigint NOT NULL
);

CREATE INDEX IF NOT EXISTS stephen_dcx_forum_comments_post_created_idx
ON stephen_dcx_forum_comments(forum_post_id, created_at_ts_ms ASC, id ASC);

CREATE TABLE IF NOT EXISTS stephen_dcx_trade_threads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_id bigint NOT NULL REFERENCES stephen_dcx_trades(id) ON DELETE CASCADE,
    trade_publication_id bigint REFERENCES stephen_dcx_trade_publications(id) ON DELETE SET NULL,
    owner_user_id bigint NOT NULL REFERENCES stephen_dcx_users(id) ON DELETE CASCADE,
    counterparty_user_id bigint NOT NULL REFERENCES stephen_dcx_users(id) ON DELETE CASCADE,
    thread_status text NOT NULL DEFAULT 'open',
    thread_reference_code text NOT NULL,
    thread_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL,
    updated_at_ts_ms bigint NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS stephen_dcx_trade_threads_reference_code_key
ON stephen_dcx_trade_threads(thread_reference_code);

CREATE UNIQUE INDEX IF NOT EXISTS stephen_dcx_trade_threads_trade_counterparty_active_key
ON stephen_dcx_trade_threads(trade_id, counterparty_user_id)
WHERE thread_status IN ('open', 'closed');

CREATE INDEX IF NOT EXISTS stephen_dcx_trade_threads_owner_idx
ON stephen_dcx_trade_threads(owner_user_id, updated_at_ts_ms DESC, id DESC);

CREATE INDEX IF NOT EXISTS stephen_dcx_trade_threads_counterparty_idx
ON stephen_dcx_trade_threads(counterparty_user_id, updated_at_ts_ms DESC, id DESC);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'stephen_dcx_trade_threads_thread_status_check'
    ) THEN
        ALTER TABLE stephen_dcx_trade_threads
        ADD CONSTRAINT stephen_dcx_trade_threads_thread_status_check
        CHECK (thread_status IN ('open', 'closed', 'archived'));
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS stephen_dcx_trade_thread_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id bigint NOT NULL REFERENCES stephen_dcx_trade_threads(id) ON DELETE CASCADE,
    source_contact_message_id bigint REFERENCES stephen_dcx_contact_messages(id) ON DELETE SET NULL,
    sender_user_id bigint NOT NULL REFERENCES stephen_dcx_users(id) ON DELETE CASCADE,
    source_channel_type text NOT NULL DEFAULT 'app',
    raw_message_text text NOT NULL DEFAULT '',
    canonical_message_text text NOT NULL DEFAULT '',
    message_summary_text text NOT NULL DEFAULT '',
    language_code text NOT NULL DEFAULT 'en',
    translations_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    message_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL,
    updated_at_ts_ms bigint NOT NULL
);

CREATE INDEX IF NOT EXISTS stephen_dcx_trade_thread_messages_thread_created_idx
ON stephen_dcx_trade_thread_messages(thread_id, created_at_ts_ms ASC, id ASC);

CREATE TABLE IF NOT EXISTS stephen_dcx_outbound_interaction_routes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_type text NOT NULL,
    provider_message_id text NOT NULL,
    recipient_user_id bigint NOT NULL REFERENCES stephen_dcx_users(id) ON DELETE CASCADE,
    route_kind text NOT NULL,
    route_id bigint NOT NULL,
    channel_type text NOT NULL,
    route_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at_ts_ms bigint NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS stephen_dcx_outbound_interaction_routes_provider_message_key
ON stephen_dcx_outbound_interaction_routes(provider_type, provider_message_id);

CREATE INDEX IF NOT EXISTS stephen_dcx_outbound_interaction_routes_route_idx
ON stephen_dcx_outbound_interaction_routes(route_kind, route_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'stephen_dcx_outbound_interaction_routes_route_kind_check'
    ) THEN
        ALTER TABLE stephen_dcx_outbound_interaction_routes
        ADD CONSTRAINT stephen_dcx_outbound_interaction_routes_route_kind_check
        CHECK (route_kind IN ('trade_publication', 'trade_thread', 'forum_post', 'market_topic'));
    END IF;
END $$;
